### ISSUE TITLE
Adding a Right Statement to data published via WordLift

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#105]
As data published to the web should **always** be accompanied by _machine-readable metadata_ that describes the dataset, its means of creation and, importantly, **a statement of the rights that relate to potential re-use of the data**. This option should be given to editors in the WordLift settings. An initial implementation could include: 
- dataset title (_presumably the name of the website_)
- dataset rights 
- dataset license 

More info for the implementation can be found here: https://theodi.org/guides/publishers-guide-to-the-open-data-rights-statement-vocabulary.

**Comment by cyberandy** [comment]
It is also extremely important to clear out any thoughts on the fact that **the data produced with WordLift belongs to the user** and this is why he/she pays a recurring fee.

**Comment by Byrlyne** [comment]
I agree with cyberandy. I know I am jumping in here without having much background on WordLift, but as a former attorney, I believe whatever boilerplate language you use to convey this message (ownership rights and copyright information) must be agreed to at the time your product/service is purchased, is clearly identifiable at the point of service, AND repeated in each and every piece of correspondence you send out. This way there is no gray area, or room for a user to claim you failed to make this clear before purchase or during use, in order to avoid lawsuits. This is not one of those situations where you can bury this information in convoluted legal-ease.

**Comment by cyberandy** [comment]
@Byrlyne thanks for your input here. [WordLift](http://wordpress.org/plugins/wordlift/) (that you can test with any WordPress website as beta tester) is currently under development and aims at providing anyone with the possibility to create his/her own [knowledge graph](http://docs.wordlift.it/en/latest/key-concepts.html#knowledge-graph). It is extremely important that **ownership rights** and **usage rights** are clear regardless of the fact that the data will move back and forth from the user's local site to the cloud. Of course as we're approaching the commercialization these issues become more and more important.

**Comment by cyberandy** [comment]
Adding a single statement on the whole dataset like:

```:example2
    a dcat:Dataset ;
    dct:title "Open Products" ;
    dct:rights :example2-rights-statement;
    dct:license <http://opendatacommons.org/licenses/odbl/1.0/>.```

**Comment by mcolacino** [comment]
@cyberandy @ziodave which kind of alternative we want to provide as licences
Is it ok to refer to what suggested here for *homogeneous DB*? http://opendatacommons.org/faq/licenses/#Why_Do_You_Distinguish_Between_the_8220Database8221_and_its_8220Contents8221
I think we should provide a collection of licenses to the user instead of ask to provide a license uri

**Comment by ziodave** [comment]
I think the end-user should be able to select how s/he would like to license her/his own contents.

I believe Creative Commons is more understandable and appropriate (than ODbl) since the end user is licensing contents, this wizard gives an overview of the available choices: https://creativecommons.org/choose/

The RDFa example in the above page shows the actual vocabulary to use when describing the license, which is also described here:
 * https://creativecommons.org/ns
 * https://wiki.creativecommons.org/wiki/RDFa

Finally I don't think we should use `dcat:Dataset` which pertains to data catalogs (a direct subclass of dcmitype:Dataset, "examples include lists, tables, and databases. A dataset may be useful for direct machine processing").

We can instead use http://schema.org/WebSite or http://schema.org/Blog (or the more generic http://schema.org/CreativeWork) to define the whole dataset (these classes have a schema:license property). http://schema.org/BlogPosting(s) can be related to http://schema.org/CreativeWork subclasses using the schema:isPartOf property.

**Comment by mcolacino** [comment]
mmm *schema:isPartOf* does not seems the proper one here ... Look at the property details
![schermata 2016-03-22 alle 10 05 47](https://cloud.githubusercontent.com/assets/1022181/13946610/ee890220-f015-11e5-964f-4515a7a71716.png)

**Comment by ziodave** [comment]
never mind isPartOf: it's not required for the license definition.

**Comment by mcolacino** [comment]
So is it ok to create on RL side a resource like:

`http://data.wordlift.it/wl023/ a schema:WebSite`
`http://data.wordlift.it/wl023/ schema:license <license_uri>`
`http://data.wordlift.it/wl023/ schema:name <blog_name>`@it

And adding in WL setting a **text input** to specify the license_uri?

**Comment by ziodave** [comment]
We should create a URI for the website, maybe http://data.wordlift.it/wl023/root or /website or /site.

Maybe we can provide the user with a SELECT to choose one of the CC licenses or "other...". I think it's enough to begin with.

Later we could expand and provide more licensing information.

**Comment by cyberandy** [comment]
I would keep a clear distinction between: 

1. licensing the contents of your site (this is none of WordLift business)  
2. licensing the metadata describing the contents of your site along with the custom vocabulary (this is the WordLift feature we need)

Let's take as example [BBC Things](http://www.bbc.co.uk/things/) - the [goal here](http://www.scribd.com/doc/254179449/Friday-lunchtime-lecture-BBC-Things-joining-up-the-news-with-open-data) for them is to **open** (some of) **BBC's tagging data** to the public and **has nothing to do with the licensing of their online contents** (these are, in BBC case, fully copyrighted). The knowledge graph published by WordLift for each user is similar to BBC Things. 

WordLift licensing - following the same analogy - shall be applied to the metadata published on _data.wordlift.it_ (or on their own custom URL) but should not be applied to the entire website.

**Comment by ziodave** [comment]
The Blog posts are published as Linked Data as well, should we then decide not to publish then?

We can use http://schema.org/CreativeWork instead of /Website or /Blog in case.

**Comment by cyberandy** [comment]
For the blog post, here is what I can see right now as [lod](http://lodview.it/lodview/?IRI=http://data.wordlift.it/wl049/post/id/1135) - the example is from v. 3.4 - and this is _metadata-only_ (with the only exception for the image). 

Generally speaking I would prefer to consider the user's graph created with WL as Dbpedia, Freebase and Wikidata and these are commonly referred as datasets rather than CreativeWork. WDYT?

**Comment by ziodave** [comment]
dcat:Dataset?

**Comment by cyberandy** [comment]
it sounds reasonable to use `dcat:Dataset` or the schema.org class `https://schema.org/Dataset` (Thing > CreativeWork > Dataset) that is based upon W3C DCAT and "benefits from collaboration around the DCAT, ADMS and VoID vocabularies". More info on: http://www.w3.org/wiki/WebSchemas/Datasets.

**Comment by ziodave** [comment]
The thing is that I don't think that /Dataset is an appropriate term.

**Comment by cyberandy** [comment]
- BBC Things is a /Dataset
- Dbpedia is a /Dataset 
- Wikidata is a /Dataset 
- data.wordlift.it/wl023/ is a ...

**Comment by ziodave** [comment]
We can rely on what Wikidata is doing with the dataset dump:

https://query.wikidata.org/#select%20distinct%20%3Fp%20%3Fo%20where%20%7B%0A%20%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23Dump%3E%20%3Fp%20%3Fo%0A%7D%0Alimit%20100

and export the following predicates:

```
<http://wikiba.se/ontology#Dump>  rdf:type	schema:Dataset
<http://wikiba.se/ontology#Dump>  <http://creativecommons.org/ns#license>	<http://creativecommons.org/publicdomain/zero/1.0/>
<http://wikiba.se/ontology#Dump>  schema:softwareVersion	0.0.1
<http://wikiba.se/ontology#Dump>  schema:dateModified	2015-11-30T23:00:04Z
```
