### ISSUE TITLE
Do not output mainEntityOfPage when not supported

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#1114]
Actually we need more details on this one because `mainEntityOfPage` applies to `Thing` so to any type.

https://schema.org/mainEntityOfPage

To reproduce set an entity as `Occupation`: the `mainEntityOfPage` property isn't being output.

Expected Behavior is that `mainEntityOfPage` property is being output.

**Comment by naveen17797** [comment]
1.I have created a post
2. Added some content on post content
3. I set the entity type to occupation
4. here is the jsonld produced by wordlift


`[{"@context":"http:\/\/schema.org","@id":"http:\/\/data.wordlift.io\/wl040\/post\/occupation","@type":"Occupation","description":"dadjkwqpej dwqpieopqwkewoq","mainEntityOfPage":"https:\/\/wordlift.localhost\/occupation\/","name":"occupation","url":""}]`

the mainEntityOfPage is published only if post content is not empty, i can get the expected behaviour without altering the code @ziodave

**Comment by ziodave** [comment]
@naveen17797 yes you're right. Turns out there is a bug in G-SDTT that was raising an error in validation. I'll close this one.
