### ISSUE TITLE
Published entities not visibile and lead to 404 error

### ISSUE THREAD

**Issue by matteoc** [insideout10/wordlift-plugin#228]
I've recorded another quick screenflow video. I am quite sure I've got a conflicting plugin.
https://dl.dropboxusercontent.com/u/83000/ScreenFlow2.mp4

Another issue is that github is not accepting videos as attachments. Like pdf's are better, right? ;-)

**Comment by cyberandy** [comment]
Hi @matteoc the previously detected conflict was with the [Redirection plugin - issue #146](https://github.com/insideout10/wordlift-plugin/issues/146). As the case was slightly different I suspect this is a different issue and we need to investigate it.

**Comment by mcolacino** [comment]
@matteoc you're the perfect beta tester :-) Could you provide your permalink structure configuration please?

**Comment by mcolacino** [comment]
I think that we should call https://codex.wordpress.org/Function_Reference/flush_rewrite_rules on plugin activation as explained below and we don't do that
![schermata 2016-01-08 alle 07 40 17](https://cloud.githubusercontent.com/assets/1022181/12192030/767234b0-b5db-11e5-8ecb-dfd7b0432db6.png)
@matteoc could you please try to update your permalink structure (even without changing your current configuration) in order to force rewrite rules flushing and check if this solves for you?

**Comment by matteoc** [comment]
@mcolacino you make me blush! I'm using Post name as a permalink structure.

I just followed your suggestions and the issue is fixed. no more 404s :)

**Comment by mcolacino** [comment]
Great! So the bug is clearly detected now ... We can proceed with the hotfix. Thanks @matteoc :-)

**Comment by mcolacino** [comment]
Resolved in 3.3.2
