### ISSUE TITLE
Location property is missing for entity type:organization

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#257]
While we allow users to populate the location for entities `type:localBusiness` we don't let users do the same for  entities `type:organization`. This is a limitation that we might need to overcome. The only concern is that we shall allow in this case the user to add multiple location for each organization. 

Further analysis on this front might be needed. This is a feature request coming from http://geobuiz.com/.

**Comment by geospatialmedia** [comment]
Hi Andrea! Thank you for taking up this request. As we maintain a calendar of events [Geospatial Events](http://geospatialworld.net/Event/index.aspx) and listing companies [Geospatial Companies Directory](http://geospatialworld.net/Company/index.aspx) a feature like this is pretty important from our perspective.

**Comment by mcolacino** [comment]
@cyberandy at the moment we allow to configure for *type:localBusiness* just https://schema.org/GeoCoordinates and not the https://schema.org/location property that is allowed instead for *type:Event*. 

Accordingly to the schema.org reference https://schema.org/GeoCoordinates can be a property of https://schema.org/Place **but not** a property of **https://schema.org/Organization**.

We could instead add to https://schema.org/Organization the property https://schema.org/location (and let inherit it to its child types). **This property could allow to set a reference to an external entity representing a Place, instead of simple coordinates**.

**Please consider that if the real need is to display both LocalBusiness and Organization entities within the geomap shortcode, we should also refactor its data retrieving logic**

Let me know if we can define this way the current issue
