### ISSUE TITLE
Absolute vs. Relative URL in <span>

### ISSUE THREAD

**Issue by tonycamero** [insideout10/wordlift-plugin#29]
Preferable to have absolute URL in markup vs. relative URL. 

Relative URL: If content moved/copied to another domain = broken
<span itemid="/entity/WordPress" id="urn:enhancement-a92002d1-20f9-ea5e-ccfe-1fa9aa98d28a" class="textannotation disambiguated wl-thing">WordPress</span>

Absolute: If content moved/copied to another domain = OK!
<span itemid="http://tonycamero.com/entity/WordPress" id="urn:enhancement-a92002d1-20f9-ea5e-ccfe-1fa9aa98d28a" class="textannotation disambiguated wl-thing">WordPress</span>

Often, content is scraped by 3rd party websites and used on other sites. Best for everyone if the markup has integrity if moved to another domain, so absolute URL is preferred.

**Comment by mcolacino** [comment]
Hi Tony ... the problem you have is due to a bug on wordlift configuration settings ... If you want to solve it quickly you can update the plugin code, deactivate and reactivate or more simply empty the application key, save and set it again ... These uri should be absolute indeed and should be Redlink absolute uri
