### ISSUE TITLE
Can't create new entity over existing annotation 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#296]
While creating a new entity over an existing annotation - an error occurs informing the user he/she shall remove the existing annotation for creating the new entity. We shall override the existing annotations ourselves avoiding this step to the user. 

![screen shot 2016-04-11 at 17 06 00](https://cloud.githubusercontent.com/assets/837037/14432293/c50d1dc4-0009-11e6-8c21-ca7bb309d6a8.png)

**Comment by ziodave** [comment]
This happens because the code checks for the following (CoffeeScript):
* `!$scope.isThereASelection`: `isThereASelection` takes the value of `selectionStatus` (which makes `isThereASelection` somewhat redundant?). `selectionStatus` is set when the TinyMCE editor fires `NodeChange`. Then `selectionStatus` takes the value returned by `EditorService.hasSelection()`: if the selection includes html code (`pattern = /<([\/]*[a-z]+)[^<]*>/`) then `selectionStatus` is set to `false`. *This makes sense, since we don't want to mess with existing HTML code especially if the selection is in the middle of an open/close tag.*
* `!$scope.annotation?`: whether a text annotation has been selected.

So we need to define how we would like to handle the following cases:
 1. the selection ends inside an annotation, e.g.:
  text <selection start>text <existing annotation start> text </selection end> text </existing annotation end>
 2. the selection contains an image or another non textual tag (we use the selected text as label), e.g.:
 text <selection start><img /></selection end> or  text <selection start><img /> text </selection end>

**Comment by cyberandy** [comment]
1. the selection ends inside an annotation: we remove the annotation 
2. the selection contains an image or another non textual tag: we warn the user and let him/her do it manually

**Comment by ziodave** [comment]
This is now fixed with #467 .
