### ISSUE TITLE
Highlighting is not working on the front-end 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#31]
A similar issue detected in the back-end can be seen in the front-end. Highlighting is NOT a vital feature and can be disabled (we shall rather give the option to the user to add automatically links to entities or not). In any case - _as of today_ - this feature doesn't work properly (_see screen-shot below_).

![image](https://cloud.githubusercontent.com/assets/837037/8571411/dd895f9c-2586-11e5-966f-437c4e11519b.png)

**Comment by mcolacino** [comment]
After an analysis this is the situtation: on test.wordlift.it Wl content filter routines are not perfomed: this means that you have on frontend the backend html code with unparsed annotation. If these routine were performed than the automated entity linking should work and highlighting could be enabled / disabled from the WL settings. The real problem here is that Wl content filter routines are executed trough the_content filter: it works at the moment only for that themes which use the_content() to print the content post.

**Comment by pieroit** [comment]
Some notes:
- schema.org markup is added only in the single page templates ( `is_single() == true` ), because doing it also on a list of posts would slow down the CMS. Should we activate it everywhere? Or maybe cache the marked up post content?
- I have the impression that the highlighting and linking are bugged by the presence of nested annotations. For example in this case:
![image](https://cloud.githubusercontent.com/assets/6328377/9273740/a3fc31fc-428f-11e5-8362-3ad3debd6d95.png)
The markup is 
![image](https://cloud.githubusercontent.com/assets/6328377/9273760/e0ad33c6-428f-11e5-93f7-3ed80d5c745c.png)
And the editor in /wp-admin shows:
![image](https://cloud.githubusercontent.com/assets/6328377/9273809/641a30a6-4290-11e5-8137-c1498c9b27f8.png)

**Comment by mcolacino** [comment]
Overlapping annotation cleaning resolves this issue for new articles. There is also an enhancement related to this issue. See issue #70. I go to close this issue now.
