### ISSUE TITLE
Favour json-ld in place of microdata

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#310]
![image](https://cloud.githubusercontent.com/assets/837037/15753280/8a1a2006-28f2-11e6-9874-fb0aba57601c.png)

By analysing the markup on this event Google provides 4 warnings. While we currently do not support performer and offers we shall see in this case the description and the image that have been added to the blog post (http://taoroma.it/entity/tai-chi-qi-gong-borgo-antuni/). 

https://search.google.com/structured-data/testing-tool/u/0/?url#url=http%3A%2F%2Ftaoroma.it%2Fentity%2Ftai-chi-qi-gong-borgo-antuni%2F

**Comment by ziodave** [comment]
For *description*, we should add an `itemprop="description"` to the post content `div`.

For *image* it's a bit more complicated, because the featured image is usually displayed outside of the post's area. In this specific case it's even not displayed at all. We might therefore look into marking up as `image`s all the embedded images.

**Comment by ziodave** [comment]
Actually the whole fix is a bit more complex, because the event data is printed outside the post content area and it's not worth to output twice the description for that.

**Comment by ziodave** [comment]
This is actually the expected behaviour in code (we never mark the description). I am marking this issue as a feature with high priority.

**Comment by ziodave** [comment]
The function to review is `wl_content_embed_microdata` located in `wordlift_content_filter.php`. This function is recursive, i.e. loads referenced entities which call again this function (by default the recursion level is set to 3).

**Comment by ziodave** [comment]
@cyberandy did you propose to remove microdata in favour of JSON-LD?

**Comment by ziodave** [comment]
I'd like to expand the conversation here to JSON-LD, since it's the [_recommended_ way](https://developers.google.com/search/docs/guides/intro-structured-data) of embedding ld data in the page.

![image](https://cloud.githubusercontent.com/assets/11438/18341591/5333ffb8-75b3-11e6-91f3-9a545d2ebe8b.png)

It's important to note the following principles:

* JSON-LD is embedded the page head (= no async loading), "Markup is placed inside a script tag in the head of the HTML page.". However there might be still hope as "Google can read JSON-LD data when it is dynamically injected into the page's contents", see the [experiments](http://www.centrical.com/test/google-json-ld-and-javascript-crawling-and-indexing-test.html).
* we're going to repeat the content data (= no solution to "my page size increased")
* obviously we cannot use the post content as _description_, as it would be excessive to repeat the page content in the page's head and there's no way to reference in-page content from JSON-LD (one of the main JSON-LD advantages is that is separated from the presentation). So either empty _descriptions_ or we can envision using the post excerpt.

References:

1. https://developers.google.com/schemas/formats/json-ld
2. https://developers.google.com/search/docs/guides/intro-structured-data
3. http://stackoverflow.com/questions/30864619/does-json-ld-have-to-be-embedded
4. http://stackoverflow.com/questions/29064209/does-schema-org-markup-work-if-markup-is-dynamically-built-with-javascript/29066759#29066759
5. http://www.centrical.com/test/google-json-ld-and-javascript-crawling-and-indexing-test.html

**Comment by ziodave** [comment]
We need to refer to the code in `wp_push_entity...` to implement this.

To get the main type of an entity there's a global function `wl_entity_type_taxonomy_get_type`.

**Comment by ziodave** [comment]
I've been experimenting a solution, some things that we need to consider to further the implementation:

* delegating the client to load _n_ entities it's not performant and can _block_ the TimelineJS widget, it's better to have the client call 1 URL with all the entities that need to be load,
* if more than one entity references the same entity, we end up writing multiple times the referenced entity, consider flatting it and use the `@id` (see [this discussion on SO](http://stackoverflow.com/questions/34761970/schema-org-json-ld-reference)),
* this issue has an impact on the microdata publishing as well that we need to start considering, especially since we're doing some work with #309 .

**Comment by ziodave** [comment]
We need to add _description_ with the entities' excerpt.

**Comment by cyberandy** [comment]
We have still an issue with the image:  

![image](https://cloud.githubusercontent.com/assets/837037/20001757/e3fba4a0-a27d-11e6-9fbd-fdefde58ec3f.png)

http://test.wordlift.it/2012-summer-olympics/ here is the entity being analysed.
As seen on the guardian that mixes various markups on the same page - if this is too hard to reach with JSON-LD - we can add it with microdata tagging.

**Comment by ziodave** [comment]
Right, I didn't consider the image.

**Comment by ziodave** [comment]
It's fixed:

![image](https://cloud.githubusercontent.com/assets/11438/20002199/6c28f242-a288-11e6-965b-ef6f78865d0b.png)
