### ISSUE TITLE
LodLive: Expand Related Resources is no longer working 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#311]
![image](https://cloud.githubusercontent.com/assets/837037/15781699/a27ef30a-29a7-11e6-926d-58e34572a174.png)

There are two errors in the Javascript console that seem to prevent the expansion to work properly on LodLive:

- Failed to load resource: the server responded with a status of 404 (Not Found)
- Failed to load resource: the server responded with a status of 500 (Internal Server Error)

http://en.lodlive.it/?http://data.wordlift.it/wl049/post/camminando_con_-_si_presenta

**Comment by mcolacino** [comment]
LodLive tries to execute the following url against WLS

http://data.wordlift.it/sparql?output=json&format=application/json&timeout=0&query=select%20*%20where%20%7B%3Fa%20%3Fb%20%3Fc%7D%20LIMIT%201&callback=lodlive

it seems a *JSONP* request in order to execute the following **sparql query** on the dataset
`select * where {?a ?b ?c} LIMIT 1`

The /sparql endpoint is not available on WLS

Please notice that the following direct redlink api call 

https://api.redlink.io/1.0/data/sparql?out=json&query=select%20*%20where%20%7B%3Fa%20%3Fb%20%3Fc%7D%20LIMIT%201&callback=lodlive&key={KEY} 

returns something like

`{
head: {
vars: [
"a",
"b",
"c"
]
},
results: {
bindings: [
{
b: {
type: "uri",
value: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
},
c: {
type: "uri",
value: "http://schema.org/Person"
},
a: {
type: "uri",
value: "http://data.wordlift.it/wl015/user/dr7oiwu0louyjfwb423fui"
}
}
]
}
}`

Further we have this second call returning a *HTTP 500*

http://lodview.it/simple-proxy/resourceProxy/?uri=http%3A%2F%2Fdata.wordlift.it%2Fwl049%2Fpost%2Fcamminando_con_-_si_presenta&query=SELECT%20DISTINCT%20*%20WHERE%20%7B%20%3Chttp%3A%2F%2Fdata.wordlift.it%2Fwl049%2Fpost%2Fcamminando_con_-_si_presenta%3E%20%3Fproperty%20%3Fobject.%20FILTER(%3Fproperty%20!%3D%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageWikiLink%3E)%7D%20%20ORDER%20BY%20DESC(%3Fproperty)%20%20LIMIT%20100&callback=lodlive

@david: shall we proxy the sparql endpoint on WLS for the first problem?
@cyberandy: shall we open an issue on lodview for the second call?

**Comment by ziodave** [comment]
I spoke with @dvcama, it's due to their proxy which needs to be reactivated, hopefully tomorrow.

**Comment by dvcama** [comment]
hello guys,
the proxy is back again
for the future I have shared the code here https://github.com/dvcama/resource-to-sparqlresult/releases/tag/1.0.0 

have a nice day

**Comment by cyberandy** [comment]
Issue has been closed successfully
