### ISSUE TITLE
Add an Event Widget 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#314]
This widget displays a selection of future events by presenting: 
- title of the widget (i.e. "Next events") 
- date of the event  
- title of the event
- date and time of the event
- link to the entity-event page
- feature image of the event

The editor shall chose the number of events to be displayed (i.e. "Number of events to show:") and all events shall be filtered by the current `date:time` to make sure only future events are presented. 

A similar widget is provided by Facebook (see attached)  
![image](https://cloud.githubusercontent.com/assets/837037/16523600/880db30e-3fa4-11e6-8389-7cfa191732ca.png)

**Comment by wanbinkimoon** [comment]
## Frontend 
Here a couple of solutions. In these mocks, we have to intend both the location and the event name as `a` tag linked in one case to the entity location page and in the other to the entity event page. 

![future events - two copy](https://cloud.githubusercontent.com/assets/10087639/24356627/04a383ce-12fb-11e7-841c-7bcaec7e39f6.png)
![future events - two copy 2](https://cloud.githubusercontent.com/assets/10087639/24356626/04a143a2-12fb-11e7-999e-00e7ffb18d7f.png)

## Settings
Here we have some basic settings for the widget, this panel is supposed to show as a standard WordPress widget settings pane.

![future events - backend widget](https://cloud.githubusercontent.com/assets/10087639/24356704/5f156994-12fb-11e7-8013-3d16fdbadbf3.png)

**Comment by ziodave** [comment]
@wanbinkimoon pls

- [ ] make an example with longer titles, longer descriptions and longer places' names.
- [ ] should we consider the year? Can you make an example for Christmas/New Year's Eve events?
- [ ] what happens if the event doesn't have a thumbnail?
- [ ] is there a different display for events that also have an end date?

**Comment by wanbinkimoon** [comment]
@ziodave here some thought I could have shared before:

**Let's truncate the text**
I think 3 rows which mean a set of 110-120 characters could be enough to show a title wich need to preview the event, let's keep in mind that this is a preview widget, not a fully consultable page. After those amount of characters, I think we could truncate the text without harming no content. Even if a `title` attribute is needed.  

**I think we could avoid the year.**
Since this is a preview widget for **future events** I think we can suppose that if an event is showed will take place in the future so the next `1 Jan`

I'm trying new solutions for the last two issues you highlighted.

**Comment by ziodave** [comment]
Ok, pls provide mockup with the above considerations, so that we can visually feel them.

**Comment by wanbinkimoon** [comment]
Here the mock wich contains the consideration discussed before. 
I even added an `RSS Feed` button as requested by @cyberandy.

![future events - four](https://cloud.githubusercontent.com/assets/10087639/24357947/b2227e84-12ff-11e7-9b1e-cbd708395236.png)

**Comment by ziodave** [comment]
* [ ] What about times, should we include times as well?

**Comment by wanbinkimoon** [comment]
I don't think that time is relevant in this scenario. 
I think this widget should just display a glimpse of future events which the user can fully display on their dedicated pages. 
Although we can provide some hidden content which can be displayed by the user just by clicking on a dedicated CTA. 
Here an example.

**Collapsed event**
![close](https://cloud.githubusercontent.com/assets/10087639/24359081/89bc8e86-1303-11e7-815b-1859a871b159.png)

**Expanded event**
The height of the details panel is supposed to be the double of the event tile so to hide the others events showed in the widget. 
![open](https://cloud.githubusercontent.com/assets/10087639/24359092/928b9462-1303-11e7-8e04-9b7d437b3537.png)

**Comment by wanbinkimoon** [comment]
On a second thought, I think we can even consider a couple of new solutions: 

** Solution One**
We could use the date module to host the time in case no end date is provided. 
![future events - five](https://cloud.githubusercontent.com/assets/10087639/24360565/fa00fdb8-1307-11e7-8f3c-22b6cec5a65e.png)

** Solution Two**
We could shrink the location section in order to free up some space for the time in the case is declared. 
![future events - four copy](https://cloud.githubusercontent.com/assets/10087639/24360625/1a26c410-1308-11e7-9a0e-2e6072688aa0.png)

**Comment by cyberandy** [comment]
+1 for Solution Two
