### ISSUE TITLE
Disable importing SVGs from analysis

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#325]
SVG images are not rendered when used as featured images, see: 

http://test.wordlift.it/entity/facebook/

![screen shot 2016-07-28 at 16 31 23](https://cloud.githubusercontent.com/assets/18528457/17216456/0d257134-54e1-11e6-8f99-c716ff84eaee.png)

![pasted_image_at_2016_07_27_12_29](https://cloud.githubusercontent.com/assets/18528457/17216490/2fca3e40-54e1-11e6-8ac2-944e0dd2e110.png)
We should suggest not to use or don't allow SVG file to be uploaded as feature images.

**Comment by markkap** [comment]
Generally SVG images are not allowed to be uploaded in wordpress, and wordpress can not calculate some relatively basic things that are required to use an image as a featured  image like generating several sizes of it.

Can look into how PDFs are prevented from becoming featured and replicate the logic, but not sure it is worth the time.

**Comment by ziodave** [comment]
I think we should filter out the SVGs from the analysis' results, what do you think @cyberandy ?

**Comment by cyberandy** [comment]
It is not totally irrelevant - I don't have exact figures but a lot of SVG files right now are coming back from the analysis. Assuming we have alternatives yes we could prevent SVG from being sent to the user but I have the impression that in some cases we will end up with no images at all if we exclude SVG. Flags for instance - afaik - are mostly available as SVG only. It's really mostly a cosmetic issue since the images do work in the front-end.

Here is a snapshot of all SVG files we've on our test installation.   

![image](https://cloud.githubusercontent.com/assets/837037/24149313/60495b94-0e42-11e7-8b5a-85fe96778255.png)

**Comment by ziodave** [comment]
Fact is that SVG are simply unsupported in WordPress, therefore we shouldn't load them in WP, see https://www.bjornjohansen.no/svg-in-wordpress

**Comment by ziodave** [comment]
This is being addressed in the context of #715 .
