### ISSUE TITLE
Allow more actions on entity tiles within the disambiguation widget

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#335]
Entity tiles within backend widget has to be refactored in order to allow more action types the tiles: 
At the moment we have the following scenarios:
1. Entities can be selected but not linked;
2. Entities can be selected and linked;
3. Entities can be unselected

**UI refactoring / enhancement is required**
**Wireframe are required here**

This issue is related to #309

**Comment by wanbinkimoon** [comment]
See #309

**Comment by ziodave** [comment]
Work on this is happening on [309_selection_no_link](https://github.com/insideout10/wordlift-plugin/tree/309_selection_no_link).

**Comment by wanbinkimoon** [comment]
This issue is related to a widely discussed topic: entity tiles need to be redesigned to improve comprehensibility and actions on annotations.
At the moment we are evaluating a wide range of solutions, in this GIF here one of the solutions proposed. 
![wl 3 7 entity tile animation 2](https://cloud.githubusercontent.com/assets/10087639/20002577/d56f82a4-a281-11e6-9c08-9cb752cd2e36.gif)

**Comment by cyberandy** [comment]
On this one we keep receiving feedback - it's top priority already.

**Comment by wanbinkimoon** [comment]
The _classification box_ is a **core** region of our plugin. This panel collects a lot of what WordLift does and how to manage it. I think we need to simplify this area in order to appear less scary to our users.  
  
Keeping this in mind I have considered the actual construction of the region and extracted the core functionality both of the **panel** and the **tiles** we have inside. 

## Panel
Actual panel
![screen shot 2016-12-22 at 11 07 46](https://cloud.githubusercontent.com/assets/10087639/21422193/e5bd48c8-c836-11e6-9cad-fd56e4b35078.png)

### Panel functionalities
   1. Contains the entity tiles
   2. Organize the tiles in **4** sections:
      a. what
      b. who
      c. where
      d. when

### Panel issues
   1. In case of several entities the panel has not limit of `height`
   2. There is no actual way of filtering the tiles 
   3. Is hard to comprehend where the panel belongs when is open 

### My proposal 
   1. Add a filter tab on top that allow the user to filter the entities based on the  category
   2. limit the `height` of the inner panel at `328px` and add property `overflow-y: auto` – this height permits us to fit up to **9** entities without scrolling.

![wl classification box 7 copy](https://cloud.githubusercontent.com/assets/10087639/21422338/811a6fbc-c837-11e6-9920-5fdca4a9bf7a.png)  ![widget 2](https://cloud.githubusercontent.com/assets/10087639/21422363/9cdea7e0-c837-11e6-97e3-953f81523d76.gif)

## Entity tiles
Actual entity tile – the first is not selected while the second is.
![screen shot 2016-12-22 at 11 20 08](https://cloud.githubusercontent.com/assets/10087639/21422581/9f331aac-c838-11e6-9878-1d3799dc61ce.png)

### Entity tiles functionalities
   1. Select the entity.
   2. Displays the number of occurrences.
   3. Displays if the entity is locally edited or not – this is **my suggestion**, at the moment the tile displays if the entity has been imported or is still in a remote server. 
   4. Allows a quick edit – the specs of this section will be discussed in a separate issue.
   5. Displays the `schema.org` classification type.
   6. Enable/Disable a global link on every entity annotation – **new functionality**

### Entity tiles problems
   1. At the moment tiles are more a list than single entities.
   2. Users have noticed that the iconography is confusing and not clear.
   3. Space is not optimised.

### My proposal
   1. Considers tiles as individual elements.
   2. Removes the bigger part of the iconography in favour of explicit text and widely known symbols.
   3. Cleans up the space and hides secondary functionalities. 
   4. Allows us to enable multiples spaces.
   5. Allows un – in a future moment – to nest `schema.org` classification. 

#### Entity listed but **not selected**
   1. Entity name.

![animation tile 1 g copy](https://cloud.githubusercontent.com/assets/10087639/21423973/2905cdea-c840-11e6-90cb-609f62ac2460.png)


#### Entity listed and selected but **not edited**
In this tile from the left:
   1. Red bullet highlights a _virgin_ entity and appears only if the entity has been selected on the post the user is working on. 
   2. Number of occurrences – allows double digits.

![animation tile 1 g copy 4](https://cloud.githubusercontent.com/assets/10087639/21423961/21285bb0-c840-11e6-99f1-fa88b08cdf96.png)


#### Entity listed, selected and **edited**

![animation tile 1 g copy](https://cloud.githubusercontent.com/assets/10087639/21423721/d234b838-c83e-11e6-9e98-8faf65449b73.png)

#### Entity listed, selected and edited with **mouse hover** on the entity name.

![animation tile 1 g copy 2](https://cloud.githubusercontent.com/assets/10087639/21423766/0f355e90-c83f-11e6-9c0f-33008cccea67.png)

#### Entity listed, selected and edited with **internal panel open**.
The panel shows up when the users click on the entity name. This `span` has a limited width of `200px`.   
In this mock from the left:
   1. Navigation arrows
   2. Global link switch
   3. `schema.org` categorization.
   4. Quick edit icon. 

![animation tile 1 g copy 3](https://cloud.githubusercontent.com/assets/10087639/21423770/1870ebc8-c83f-11e6-8f0b-91b246222f36.png)

**Comment by ziodave** [comment]
Some digging is required to better understand how the _classification box_ currently.

First of all there's a _configuration_ object:

```
window.wordlift.classificationBoxes = [
   {
      "id":"what",
      "label":"What",
      "registeredTypes":[
         "thing",
         "creative-work"
      ],
      "selectedEntities":[

      ]
   },
   {
      "id":"who",
      "label":"Who",
      "registeredTypes":[
         "organization",
         "person",
         "local-business"
      ],
      "selectedEntities":[

      ]
   },
   {
      "id":"where",
      "label":"Where",
      "registeredTypes":[
         "place"
      ],
      "selectedEntities":[

      ]
   },
   {
      "id":"when",
      "label":"When",
      "registeredTypes":[
         "event"
      ],
      "selectedEntities":[

      ]
   }
];
```

**Comment by ziodave** [comment]
All the above is irrelevant for entity (de)selection. The `entityDeselected` event is actually catch by this:
```
  $rootScope.$on "entityDeselected", (event, entity, annotationId) ->
    if annotationId?
      dedisambiguate annotationId, entity
    else
      for id, annotation of entity.annotations
        dedisambiguate annotation.id, entity
        
    occurrences = currentOccurencesForEntity entity.id    
    $rootScope.$broadcast "updateOccurencesForEntity", entity.id, occurrences
```

which then removes the `occurrences` from the `entity` caused the `entity` to be `deselected`.

Therefore to detect the selection state for an `entity` it's better to hook to the `updateOccurencesForEntity` event. This event is fired in 3 different places in `EditorService`.

**Comment by ziodave** [comment]
Remaining tasks:

- [ ] do we need a custom font? (OpenSans)
- [ ] fix styles
- [ ] implement grouping
- [ ] fix order
- [ ] unit tests
- [ ] cross-browsing and e2e tests

**Comment by ziodave** [comment]
@wanbinkimoon tiles do not show in IE11, can you please check? thanks!

**Comment by ziodave** [comment]
Still 2 open issues here:

- [ ] @ziodave : IE11 doesn't display the tiles,
- [ ] @wanbinkimoon : long titles do not display correctly:

![image](https://cloud.githubusercontent.com/assets/11438/23337962/a716179a-fc06-11e6-9fa9-80d88051267d.png)

**Comment by wanbinkimoon** [comment]
Regarding the last point of the issue I think we could use some kind of animation like the one i'm gonna propos in the codepen. 
Unfortunally in order to animate the trasiction we need to calculate the difference between the internal `span` and the wrapper. 

View the Codepen [here](http://codepen.io/wanbinkimoon/pen/vxOpMN?editors=0011)
