### ISSUE TITLE
Deselecting the last entity in a "W" section doesn't work  

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#34]
When trying to remove a selected entity by either clicking on the "x" on the button or by unchecking the entity below nothing happens. 

![image](https://cloud.githubusercontent.com/assets/837037/8616319/9c810930-26fa-11e5-9fa9-942195bc3aa8.png)

Here is the console log: 

![image](https://cloud.githubusercontent.com/assets/837037/8616360/f35101e8-26fa-11e5-8e87-4e8220a78342.png)

The blog post being tested is: http://test.wordlift.it/wp-admin/post.php?post=1723&action=edit&message=1

**Comment by mcolacino** [comment]
The deselection order is not the root cause.

Here is the error in the log that let the widget crash
![schermata 2015-07-10 alle 20 21 11](https://cloud.githubusercontent.com/assets/1022181/8625817/575c8fb8-2741-11e5-84fc-3e4953cd1291.png)

**Comment by mcolacino** [comment]
This error is due to the sameAs property that is set to 'null'. An empty array is expected instead.

**Comment by mcolacino** [comment]
The main error is solved. The specific one for "Nasa" is due to the fact that in the code there is an empty annotation

<span id="urn:local-text-annotation-1yr29ekfw6vl5wmic3zdus3bxhpeewmi" class="textannotation disambiguated wl-organization" itemid="http://data.redlink.io/91/be2/entity/NASA"></span>

**Comment by mcolacino** [comment]
This issue is solved: a selected entity that refers to a broken (empty) annotation should not be set as 'selected'. The js layer properly manage this case now: it skips entity selection if there are no valid occurrences for a given entity and sanitizes the content html markup accordingly. A post save is required to reflect changes on wordpress database.
