### ISSUE TITLE
Streamlining the setup process of WordLift

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#364]
This issue might eventually be divided in multiple ones. Here is a quick summary: we had already few clients getting stuck before activating the plugin key. Main reasons being the following: 
1. when copying the key some user keep a white space in the string and the key doesn't work (we need to trim any white space)
2. providing a simple text in case something goes wrong also is of good help i.e. "the WordLift key is a string of x characters ..."  
3. the change of the entity path needs to be explained with a simple question i.e. "All your entities will be published under the path http://yourwebsite/entity/. Would you like to personalise this path with your own custom string?" If yes - "Please add the string that will replace the entity part in the path" (or something similar)  
4. making the key hidden just like a password also would be good.

I am setting the priority high as we had several issues here already.

**Comment by ziodave** [comment]
@cyberandy pls update this issue.

**Comment by wanbinkimoon** [comment]
In order to simplify the activation process we designed this wizard builded in 5 steps  
![wl activation step 1 v3](https://cloud.githubusercontent.com/assets/10087639/20096292/84a54586-a5a9-11e6-90fb-78b0a987fba4.png)
![wl activation step 2 v3](https://cloud.githubusercontent.com/assets/10087639/20096293/84c5f646-a5a9-11e6-93f9-694bf5b60b74.png)
![wl activation step 3 v3](https://cloud.githubusercontent.com/assets/10087639/20096294/84d5659a-a5a9-11e6-8f63-1591a8bcbf33.png)
![wl activation step 4 v3](https://cloud.githubusercontent.com/assets/10087639/20096295/84d90204-a5a9-11e6-9c51-deaac6d5f7e3.png)
![wl activation step 5 v3](https://cloud.githubusercontent.com/assets/10087639/20096297/84da65cc-a5a9-11e6-8b91-b5c5a2fdd43b.png)
![iphone 7 activation step 1 v4](https://cloud.githubusercontent.com/assets/10087639/20096296/84da6522-a5a9-11e6-9d73-960d4189765a.png)
![iphone 7 activation step 2 v4](https://cloud.githubusercontent.com/assets/10087639/20096298/84e11e62-a5a9-11e6-86f4-2a37aa54a5b5.png)
![iphone 7 activation step 3 v4](https://cloud.githubusercontent.com/assets/10087639/20096299/84e29d8c-a5a9-11e6-9cd1-8f946cb80b15.png)
![iphone 7 activation step 4 v4](https://cloud.githubusercontent.com/assets/10087639/20096302/84f1f200-a5a9-11e6-8e3b-83bc7853a58c.png)
![iphone 7 activation step 5 v4](https://cloud.githubusercontent.com/assets/10087639/20096303/84f705d8-a5a9-11e6-8b37-9a9a6f749ba9.png)

**Comment by wanbinkimoon** [comment]
Push mechanism is supposed to behave like this.
![first_activation](https://cloud.githubusercontent.com/assets/10087639/20098159/b09e418e-a5b2-11e6-9054-79669529f2bc.gif)

**Comment by wanbinkimoon** [comment]
Push mechanism is supposed to behave like this.

![first_activation](https://cloud.githubusercontent.com/assets/10087639/20098299/6f40a7c6-a5b3-11e6-9945-2f89b1c92228.gif)

**Comment by ziodave** [comment]
I am rewriting the issue here #397

**Comment by ziodave** [comment]
This issue is now superseded by #397
