### ISSUE TITLE
Newly created entity doesn't appear after saving draft and/or publishing

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#39]
I've tried the following: 

1. creating a new blog post (currently in published privately on: http://test.wordlift.it/wp-admin/post.php?post=1827&action=edit&message=1)
2. adding a new entity for the WHO - the entity in this case is L’Oréal that for some reason was not recognised in the first place (I was though able to successfully find under the sameAs suggestions 
http://dbpedia.org/resource/L'Oréal - and this felt nice)
3. choosing the newly created entity as WHO   
4. saving the post as draft - and ... **losing the entity that I had previously created and associated with the WHO of the article**

The entity is available in the vocabulary hence it exists but it is no longer present in the blog post for no reason.

**Comment by mcolacino** [comment]
The issue was related to utf8 chars in the entity uri. It's now fixed. The fix can be seen here http://test.wordlift.it/wp-admin/post.php?post=2315&action=edit
The fix use the native wp function sanitize_title()
https://codex.wordpress.org/Function_Reference/sanitize_title
Please notice that entity uris are now managed differently ... This means that all old posts / entity has to be created again in order to be sure to avoid inconsistent data.

**Comment by mcolacino** [comment]
This fix is only related to entities created from scratch when the desired entity is missing in the analysis results.
