### ISSUE TITLE
Argument #2 should be an array

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#413]
On a WordPress install with WordLift and wordpress-seo, if the former is uninstalled, the second raises the following error on edit post pages:

> Warning: array_map(): Argument #2 should be an array in
wp-content/plugins/wordpress-seo/admin/class-primary-term-admin.php
on line 198

_Ref. Ticket#2016120810000012_

**Comment by markkap** [comment]
@ziodave I didn't succeed to recreate it on a trivial setup, but digging into the yoast code it seems that the following scenario is what ends up emitting the error.

1. User has object caching on his server
2. Yoast uses cache to store the list of hierarchical taxonomies
3. Yoast never clears the cache when a taxonomy is removed
4. The entity type is an hierarchical
5. After wordlift uninstalled  the entity type taxonomy is no longer there
6. When displaying the "primary category" setting for the hierarchical taxonomies of a post, yoast tries to loop over them
7. but since the cache is stale it tries to call get_terms for the taxonomy which fails with a wp_error since the taxonomy is not there any longer.

If I am correct, not sure we can do anything about it. Yoast code needs to be updated to check for get_terms  returning errors, or find a way to invalidate its cache when a taxonomy is removed (which might be hard)

**Comment by markkap** [comment]
@ziodave, as we are not going to do anything about it for now (and not sure we can), I remove the milestone to reduce clutter
