### ISSUE TITLE
Add Publisher field to WordLift Setting page

### ISSUE THREAD

**Issue by novedavi** [insideout10/wordlift-plugin#427]
We need to offer to our existing client the same option of choosing the publisher included in the new Setup Wizard.

The Publisher field in the setting page should allow users to search in their vocabulary for existing entities that could work as publishers.
See example from CamminandoCon:
![screen shot 2016-12-27 at 17 49 07](https://cloud.githubusercontent.com/assets/18528457/21504165/cb6f74e4-cc5c-11e6-9714-02f792776a32.png)

I should be able to choose the entity:organizazion CamminandoCon already in my vocabulary.

**Comment by ziodave** [comment]
We need to the define the UX first.

**Comment by ziodave** [comment]
@wanbinkimoon we need your help here to define the user experience. I think the most "complex" setting is the publisher where we shall let the user select an existing Organization (or Person), or create it in-page in a similar way we do in the set-up screen.

To select an existing Organization (or Person) we could use a select like _select2_ which we can [customize to provide the entity's details inline](https://select2.github.io/examples.html#data-ajax), e.g.:

![image](https://cloud.githubusercontent.com/assets/11438/22504579/bb49d958-e87f-11e6-8ecc-6402dd6c315e.png)

**Comment by wanbinkimoon** [comment]
@ziodave i'm on the same page, at the moment i'm looking for a similar solution but based on reac instead of jQuery, do you think react could be used there?

**Comment by ziodave** [comment]
@wanbinkimoon I think React is overblown here and could slow down development.

**Comment by wanbinkimoon** [comment]
@ziodave ok, that was my fear

**Comment by wanbinkimoon** [comment]
This is my workflow suggestion, everything done in the select can be done via **select2** as requested
![wl-widget-faceted](https://cloud.githubusercontent.com/assets/10087639/22519467/a63409ae-e8b0-11e6-8217-04d2fbd914a3.gif)


Start/End State in this separate mock 
![desktop copy 2](https://cloud.githubusercontent.com/assets/10087639/22519532/e0a73b7e-e8b0-11e6-8894-3771eacd96c8.png)

**Comment by cyberandy** [comment]
@wanbinkimoon pls add the context of the setting page so that we can understand how this will fit with the rest or how you plan to revise also the other elements we currently have.

**Comment by ziodave** [comment]
I like the "Last updates in your Media Library" element, which I saw also in #356, but I am not sure if we'll implement it in the scope of this task, anyway it doesn't affect the rest.

**Comment by wanbinkimoon** [comment]
Here our element by itself

![valid create a new entity copy mask](https://cloud.githubusercontent.com/assets/10087639/22546476/7b7f3a0c-e93d-11e6-8979-c3b2d25ec5e3.png)


Here some context 

![artboard](https://cloud.githubusercontent.com/assets/10087639/22546440/5b84ea6c-e93d-11e6-919a-d6bb2bfb18cb.png)

**Comment by ziodave** [comment]
I think we should stick to WP's UI as much as possible, e.g.:

![image](https://cloud.githubusercontent.com/assets/11438/22546527/23150564-e946-11e6-9a91-37cfa78ecc19.png)

The UI is also responsive:

![image](https://cloud.githubusercontent.com/assets/11438/22546543/33707f6a-e946-11e6-9fc2-0fc6aa380bdf.png)

**Comment by wanbinkimoon** [comment]
Ok, lets improve a little the experience with some micro changes

1.  Let's set the width of the `input[type="text"]` to `480px` when possible or `100%` in smaller screens ( this is already supported by worpress) 
2. Let's insert this select using wordpress tyles and adding minimum information to the user. 

This is how i expect the select to work

![artboard](https://cloud.githubusercontent.com/assets/10087639/22547942/6e304c54-e944-11e6-8ef3-22ffa6ffdb96.png)

And this is how i think should work the "create new entity"

![artboard2](https://cloud.githubusercontent.com/assets/10087639/22547966/7bf04cd6-e944-11e6-8bb7-57ab84d9584b.png)

**Comment by wanbinkimoon** [comment]
Here some construction infos

![artboard2](https://cloud.githubusercontent.com/assets/10087639/22548094/3161d8d2-e945-11e6-87e2-79de0202fc21.png)
![artboard](https://cloud.githubusercontent.com/assets/10087639/22548095/3164323a-e945-11e6-9b8b-3f9c09b86e94.png)

**Comment by wanbinkimoon** [comment]
Here the new mocks with the link that allow the user to jump from one option  to the other. 

![artboard](https://cloud.githubusercontent.com/assets/10087639/22560115/a68b8d64-e973-11e6-9b4d-662f9df46235.png)
![artboard 2](https://cloud.githubusercontent.com/assets/10087639/22560116/a68d2fc0-e973-11e6-8db0-4089b4062526.png)

We need also to insert description as permitted by wordpress. Here the copy:

#### WordLift key
Insert the WordLift Key [<--- provide link to www.wordlift.io/blogger ] you received via email.

#### Entity Base Path
All new pages created with WordLift, will be stored inside your internal vocabulary. You can customize the url pattern of these pages in the field below. Check our FAQs [<-- provide link to https://wordlift.io/wordlift-user-faqs/#10-why-and-how-should-i-customize-the-url-of-the-entity-pages-created-in-my-vocabulary ] if you need more info.

#### Site Language
Each WordLift Key can be used only in one language. Pick yours.

## Publisher 
Are you going to publish as an individual or as a company?

**Comment by wanbinkimoon** [comment]
@markkap we also rmoved the small phrase under the `h1`

**Comment by markkap** [comment]
@wanbinkimoon There is a problem with having the switch between "select existing" and "create a new one" placed as it is right now below the publisher label. It is both on user expectation level, that this side of the settings screen is reserved for labels of the inputs on the right hand side, ad therefor it is "static" in nature, and the API used to create the relevant  "form" that expects a static label to display there. 

What might be better is maybe to treat that area as a section and not as a setting (because it is really 3 settings and not one in any case), get everything to be below the "publisher" label and than maybe there will be more freedom in associating the option selected on the left with the input request on the right.

Another thing, I am going to use "WordLift Settings" as the title of the screen instead of the "general settings" in the screenshot, unless there is any objection.

**Comment by markkap** [comment]
@ziodave should I remove the "advanced" settings code while doing this?

**Comment by markkap** [comment]
@ziodave should I remove the "advanced" settings code while doing this?

**Comment by markkap** [comment]
just to make sure it is not just an oversight in the design, should the user be able to change the "entity base path" after the first install?

**Comment by wanbinkimoon** [comment]
@markkap Correct, the user should **not** be able to change the entity base path after the first install.

Regarding the "select existing"-"create a new one" issue, i think your solution could fits ur needs but i'd like to see a visual example of what you mean, can you provide one? (even a pen sketch if totally fine)

**Comment by ziodave** [comment]
@markkap yes please remove the legacy Advanced Settings code.

As for the entity path, you have to disable the textbox (and changing the setting) if there are one or more entities created in WP (entity post count), *not* after first install (this is also the current behavior).

**Comment by ziodave** [comment]
> There is a problem with having the switch between "select existing" and "create a new one" placed as it is right now below the publisher label. It is both on user expectation level, that this side of the settings screen is reserved for labels of the inputs on the right hand side, and therefor it is "static" in nature, and the API used to create the relevant "form" that expects a static label to display there.

I think also using links to choose between new or existing it's confusing.

**Comment by markkap** [comment]
I don't know... Maybe we should take a step back, and first decide how the configured information should be displayed, maybe once we have that part it will be easier to decide where to place the selection/creation switch. At least I assume that some things like updating the logo and name should be available from the settings screen.

The most relevant example I could find in wordpress plugins is actually the way yoast SEO configures the same information. You can see it under the "Your Info" tab in the settinngs. It basically breaks it into two sections, one in which the type is configured and another one that is being displayed based on what was selected as the type, contains the actual fields.

![general yoast seo wordlift wordpress](https://cloud.githubusercontent.com/assets/1206170/22647710/cc428f48-ec7b-11e6-9beb-698601a17b3b.png)

![general yoast seo wordlift wordpress 1](https://cloud.githubusercontent.com/assets/1206170/22647760/fd095922-ec7b-11e6-8837-00f1edc4b828.png)

**Comment by markkap** [comment]
@ziodave we mentioned doing key validation like it is being done in the wizard. questions
1. Do you want to follow with the same visuals and logic
2. Assuming the key currently in the system is invalid, do we just use the visuals from point 1., add a notice, or probably both? (related #453 )

**Comment by wanbinkimoon** [comment]
@markkap here the solution I presented you today :)
![artboard 2 copy](https://cloud.githubusercontent.com/assets/10087639/22666237/16137f10-ecb8-11e6-9a50-f12a444df869.png)

**Comment by markkap** [comment]
cool, I think the only issue I have left is the design and text of the "upload image" button. Technically the user will be presented with the wordpress media dialog in which he can upload and select an image, or just select it if it is already on the server, so maybe something like "upload/select image" is better text? not sure myself .... and I see that yaost uses the "upload image" (at least without "new") text as well....

The bigger issue is the color of the button which might confuse people between the upload button and the submit button. I would suggest to go with a grayish style like it is in yoast.

**Comment by wanbinkimoon** [comment]
@markkap Let's try with "Choose your image" and graysh color for the button.

**Comment by wanbinkimoon** [comment]
@markkap this is how i think te section should look and behave like 
![wl-settings-publisher-2](https://cloud.githubusercontent.com/assets/10087639/22777937/43061132-eeb5-11e6-8a1d-1866b96a548e.gif)

**Comment by markkap** [comment]
@wanbinkimoon The feature/427.... branch has now all the UI related code, please take a look and give comments.

There is one thing that needs to be decided - do we want to let the user search between the available entities (this is something that select2 enables by default). I guess it depends on how many entities might be displayed on real sites.

**Comment by ziodave** [comment]
@markkap yes, we can set minimum 3 characters, and restrict the entity types to Person and Organization. Select2 should also support pagination (and caching with some custom coding that we can add later).

**Comment by markkap** [comment]
@ziodave so you want to go full ajax with it?

**Comment by ziodave** [comment]
yes

**Comment by ziodave** [comment]
let me elaborate on that: we could make a count of Person/Organization and, if the count is less than or equal to 10 then preload everything. Otherwise use Ajax with filters.

**Comment by markkap** [comment]
ok

**Comment by wanbinkimoon** [comment]
I'd love to avoid pagination

**Comment by ziodave** [comment]
Select2 pagination is not related to UI/UX, just chunked transfers of data in the select results.

**Comment by markkap** [comment]
last commit is with AJAX support when there are more than 10 entities. @ziodave do you have any specific number of entities to be used for paging?

**Comment by ziodave** [comment]
@markkap some things we need to fix:

## File class-wordlift-admin-settings-page.php

- [ ] All comments should start with a capital letter and [end with a full stop](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#5-1-single-line-comments) or WP-code style validation will raise a warning,

- [ ] All files should have [a file header](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers),

- [ ] Do not _pollute_ the global scope, constants such as `WL_MAX_ENTITIES_WITHOUT_SEARCH` and `WL_MAX_ENTITIES_WITHOUT_AJAX` can be defined as class constants, even better we can pass them a parameters to the constructor, allowing for customization via `wp-config.php` (there we can use global constants),

- [ ] The `render_page` method includes HTML code which must be moved to a separate partial file in the _partials_ subfolder,

- [ ] I think we can remove the _advanced configuration_, since we're not using it anymore (`wl_configuration_advanced_settings_section_callback`, `if ( defined( 'WL_ENABLE_ADVANCED_CONFIGURATION' ) && WL_ENABLE_ADVANCED_CONFIGURATION ) {`, ...),

- [ ] We can remove any reference to the _Noun Project_ since we're not using it anymore,

- [ ] The function `wl_configuration_get_key()` is deprecated, pass the `Wordlift_Configuration_Service` to the instance and use `get_key` to read the key,

- [ ] By passing the `Wordlift_Configuration_Service` to the constructor we can avoid using `::get_instance()`,

- [ ] `Wordlift_Entity_Service` can be passed to the constructor and we can avoid using `::get_instance()`,

- [ ] `wl_configuration_get_site_language` can be replaced with `$this->configuration_service->get_language_code()`,

- [ ] There's an error in `publisher_section`, `wp_Query` instead of `WP_Query`; also in `possible_publisher`,

- [ ] `publisher_section`: `<style>` must be moved to an external css, html must be moved to a partial,

- [ ] `get_languages` should be removed in favor of `Wordlift_Languages::get_languages()`,

- [ ] If we're not referencing anymore the file `ISO-639-2_utf-8.txt`, then we can remove it,

- [ ] `wl_configuration_set_redlink_dataset_uri` is deprecated, use `Wordlift_Configuration_Service`,

- [ ] Consider adding a function in `Wordlift_Configuration_Service` for to replace (and deprecate) `wl_configuration_get_accounts_by_key_dataset_uri`,

- [ ] `wl_write_log` is deprecated, use `Wordlift_Log_Service` or remove the log line,

- [ ] The function doc block for `search_by_title` is incomplete.

## src/admin/class-wordlift-admin.php

- [ ] In legacy code we were passing AJAX action names via client-side settings, I don't think this is useful, only pollutes the code, we can therefore remove the following `'key_validation_action'  => 'wl_validate_key'` and use`wl_validate_key` directly in client code,

- [ ] Same here for comments, start with a capital letter, end with full-stop.

## JavaScript files

I'll look them as last thing and I'll see if I can merge them to the wordlift-admin.bundle.js file.

**Comment by ziodave** [comment]
Now there are four things left:

- [ ] html escapes
- [ ] styles
- [ ] unit tests
- [ ] e2e tests

**Comment by ziodave** [comment]
@wanbinkimoon there are still things you need to improve on the UI:

- [ ] the layout for the image preview and button:

![image](https://cloud.githubusercontent.com/assets/11438/23182126/18f9f4d8-f880-11e6-87a6-1f34450e76fe.png)

- [ ] the valid/invalid icon on WordLift's key input text

- [ ] should we also change some placeholders and button labels to make the form look more similar to the setup screen, e.g. 'Publisher's Name' to 'What's your name'? 'Select an existing image or upload a new one' to 'Add logo'?

![image](https://cloud.githubusercontent.com/assets/11438/23182237/85fba98c-f880-11e6-9a5e-465440ee93b7.png)
