### ISSUE TITLE
Exposing vocabulary and topics in the REST api

### ISSUE THREAD

**Issue by ndemoor** [insideout10/wordlift-plugin#435]
I was wondering, since the REST api was announced in WP 4.7, how the wordlift-plugin would position itself, when exposing the vocabulary and topics through this api? I see 2 scenarios:

1. Default to open it up by adding parameters in the `register_post_type` and `register_taxonomy` hooks: https://developer.wordpress.org/rest-api/adding-rest-api-support-for-custom-content-types/#registering-a-custom-post-type-with-rest-api-support
2. Leave it up to the website owner/theme developer to overwrite: https://developer.wordpress.org/rest-api/adding-rest-api-support-for-custom-content-types/#adding-rest-api-support-to-existing-content-types

It be happy to contribute the change in case scenario 1 is preferable.

**Comment by ziodave** [comment]
Hello @ndemoor, scenario 1 seems very plausible since it would allow anyone accustomed with WP's REST APIs to query the custom entity type and taxonomy using standard semantics.

This would complement other means publishers can already use to programmatically access the entities - such as the in-page JSON-LD, entities permanent URIs or full dataset in different formats (JSON-LD, RDF, TTL, ...) and SPARQL - with something more WP developers' friendly.

So, absolutely, feel free to push a PR, we'll look into releasing it in WordLift 3.10 due this month.
