### ISSUE TITLE
Text Annotations are too invasive

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#440]
Text Annotations in WP's editor are too invasive and we should define a way to hide them when they're not useful.

**Comment by ziodave** [comment]
See #414

**Comment by wanbinkimoon** [comment]
## State of things   
At the moment WordLift produces a lot of annotations and underlines in Wp text editor.
![screen shot 2017-01-16 at 18 09 08](https://cloud.githubusercontent.com/assets/10087639/21992519/04f75ef6-dc17-11e6-8dfa-51b05712b473.png)

### High level UI disasters
We also have to consider cases like this: when the text is underlined we create a chaotic UI.
![screen shot 2017-01-16 at 18 12 42](https://cloud.githubusercontent.com/assets/10087639/21992624/818d5d58-dc17-11e6-94fb-9e3e8120f6fa.png)

## Problem
We need to significantly **reduce** our visual impact in this area but still need to veicolate a least 3 types of information:

1. Entity available
2. Entity selected 
3. Entity selected and linked

### Solution analysis 

#### Previous evaluation
When we faced this UI section in a first moment i suggested this solution:

- http://codepen.io/wanbinkimoon/pen/jrzvyL

**This option can no longer be considered a possible solution.**

 
#### Possibles solutions : 1
Reduce the number of infos at just 2 avoiding the **Entity available** option and use a background with a very light opacity in order to highlight selected entities. Color may be pimped on `:hover`.
![artboard](https://cloud.githubusercontent.com/assets/10087639/21993431/156578dc-dc1b-11e6-819b-23e2a79b9228.png)

In this example consider:

- «thinking» as selected entity
- «news» as selected and `:hover` entity
-  «creative» as selected and linked

This solution is also used by medium.com for a different purpose: social highlights
![screen shot 2017-01-16 at 18 37 16](https://cloud.githubusercontent.com/assets/10087639/21993438/216817e8-dc1b-11e6-8b32-b385ae773159.png)

#### Possibles solutions : 2
Use `color` CSS property in order to change font color. 
**Cons**: this could highly interfere with user's post customizations.

![artboard](https://cloud.githubusercontent.com/assets/10087639/21993576/d3cea492-dc1b-11e6-9fdf-0e64604410d9.png)

Consider:
- «though» as a selected entity 
- «techniques» as selected and linked entity

**Comment by cyberandy** [comment]
Solution 1 seems more consistent. While better it doesn't solve entirely the problem. While writing, the annotations (nicely styled) are still invasive. Ideally we shall fade them in and out to let the editor see the underlying structure of the text only when needed. 

Lately I have looked once again closely at the infamous Xanadu project as a key reference to the evolution of web editors like WordLift. For pure inspiration the work done at that time can provide some good insight.

**Comment by ziodave** [comment]
> avoiding the Entity available option

I am not sure we want to completely abandon the text annotations.

> Ideally we shall fade them in and out to let the editor see the underlying structure of the text only when needed.

This sounds great.

**Comment by wanbinkimoon** [comment]
What if we avoid available entities until the user `:hover` the relative tile on the widget? 
Then we fade the annotation in and out so he can focus on the relative element on the page?

**Comment by ziodave** [comment]
It's not practical at all, also because the text annotation might not be visible if the text is long.

**Comment by wanbinkimoon** [comment]
This is how i would expect annotation to behave is we add an animation on them.
![wl - widget - annotation](https://cloud.githubusercontent.com/assets/10087639/22027087/faf412de-dcd2-11e6-88b6-98b254bcfe02.gif)

**Comment by wanbinkimoon** [comment]
Real case scenario:
![editor 2](https://cloud.githubusercontent.com/assets/10087639/22027155/3003d09a-dcd3-11e6-8e67-81de4498f2e4.png)

**Comment by ziodave** [comment]
I would split this to another issue: 
![image](https://cloud.githubusercontent.com/assets/11438/22202883/feaf531c-e172-11e6-9c7e-dbe30c450921.png)

When the user is typing, focus is in the editor, so we'll need to take into account "user starts/stops typing".

**Comment by cyberandy** [comment]
Here we have to keep in mind the importance of adding in any case the toggle #412

**Comment by wanbinkimoon** [comment]
Here a codepen of i expect the style of the text annotation with the in/out animation, the on/off mechanism is not related to the issue 

<p data-height="265" data-theme-id="0" data-slug-hash="EZGGPR" data-default-tab="html,result" data-user="wanbinkimoon" data-embed-version="2" data-pen-title="wl - annotation in editor - #440" class="codepen">See the Pen <a href="http://codepen.io/wanbinkimoon/pen/EZGGPR/">wl - annotation in editor - #440</a> by nicola bertelloni (<a href="http://codepen.io/wanbinkimoon">@wanbinkimoon</a>) on <a href="http://codepen.io">CodePen</a>.</p>

I think that annotation should disappear on user `:focus` on the WP editor, let's try this option showing annotations after `2500ms` after the user exits `:focus` on the WP editor.

**Comment by ziodave** [comment]
While this issue is marked _resolved_ we carefully need to assess the right styles for the following states:

* annotation
* selected annotation (i.e. clicked)
* disambiguated annotation (i.e. an entity is bound to it)
* optionally a disambiguated annotation which is getting selected

**Comment by ziodave** [comment]
- [ ] while we define colors and styles, we can use the existing styles (underlined, black and blue).

**Comment by ziodave** [comment]
* annotation: _no change_
* selected annotation (i.e. clicked): _like previous version_
* disambiguated annotation (i.e. an entity is bound to it): _like previous version_
* optionally a disambiguated annotation which is getting selected: _like previous version_
