### ISSUE TITLE
Automatically populating $HTTP_RAW_POST_DATA warning breaks WL analysis

### ISSUE THREAD

**Issue by mcolacino** [insideout10/wordlift-plugin#465]
I'm experiencing some issue on my local env.
I'm running WL on **php 5.6.25**.

With the default php.ini configuration below
![schermata 2017-02-05 alle 10 54 26](https://cloud.githubusercontent.com/assets/1022181/22625269/87ececc0-eb91-11e6-9bfd-33b68c016659.png)

I got the following **php warning** together the analysis result that of course breaks the analysis workflow. 

<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"entities":{"http://dbpedia.org/resource/Fishing":{"entityId":"http://dbpedia.org/resource/Fishing","confidence":1.0,"mainType":"thing","types":null,"label":"Pesca","description":"La pésca è un'attività commerciale e sportiva che da millenni fornisce cibo alle popolazioni insediate presso laghi, mari o fiumi. Essa consiste nella cattura del pesce utilizzando strumenti di vario tipo.","images":["http://upload.wikimedia.org/wikipedia/commons/b/b9/Stilts_fishermen_Sri_Lanka_02.jpg"],"sameAs":["http://rdf.freebase.com/ns/m.094jc"]

And this is what I found in wp logs

`
[05-Feb-2017 09:30:08 UTC] PHP Warning:  Cannot modify header information - headers already sent in /Users/mcolacino/src/greenpeace/greenpeacenews/wp-content/plugins/wordlift/modules/analyzer/wordlift_analyzer.php on line 14
`

While it is easy to solve it by changing the php.ini, please take it in consideration for further WL compliance with new php versions

**Comment by ziodave** [comment]
We're compatible from PHP 5.3 to PHP 7.1: https://travis-ci.org/insideout10/wordlift-plugin/builds/196572602 (WordLift is not accessing the `$HTTP_RAW_POST_DATA` variable).

This isn't related to WordLift or to WordPress: it's a PHP message which warns you that you're using a deprecated setting in your php.ini file.

I suggest that:
 * you update the php.ini file as requested by PHP,
 * disable PHP errors output to the http response.

The 2nd error (Cannot modify header information) it's because of PHP errors output to the http response.

**Comment by mcolacino** [comment]
cool :-)
