### ISSUE TITLE
Check compatibility with WordPress Multisite configurations 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#484]
We are gathering the requirements. The goal is to use WordLift on a multisite installation of WordPress.

**Comment by markkap** [comment]
From quick code inspection, the only obvious that will just not work properly is the logging service. Code there will need to be changed to have some indication of the sub site it "runs" on.

From my POV there are three scenarios for such an install and each needs to be inspected differently 
1. Multilingual site, in which each site is different language. This will require different install flow per each site due to language differences.

2. interconnected sites, like a shop and a blog for it, and maybe something like blogs for journalists at a newspaper This will require some code changes to move the relationships table to be "global", and all the general settings as well.

3. wordpress.com clone. In theory there might be requirement for interconnection (one user running several blogs) but I don't see operators of such things giving such options, so most likely it will be the same as item 1.

... and after running some tests it seems like right now wordlift generates too many errors to call it working. Got it actually mostly working on the main site but getting PHP errors when starting a new post, and on a sub site, just can't complete the wizard/settings with publisher setting failing to be saved.
the errors leads all to one place in the code therefor there might be some local edge case as there was nothing in the specific code to explain easily why it works on "normal" and fails on multisite.
