### ISSUE TITLE
Running the Vocabulary on a separate website

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#532]
The functional requirements are the following: 

- [ ] the main website is on a different domain/website (i.e. www.mywebsite.com)

- [ ] when adding widgets to entities pages all articles linked (i.e. from the chord widget, the navigator, the timeline or the faceted search) should point to the main website (www.mywebsite.com)

- [ ] when reading an article on the main site all internal links to the vocabulary shall be re-directed to myvocabulary.mywebsite.com

- [ ] on the widgets (chord, navigator, timeline and entity cloud) running on the main site all links to entities shall be re-directed to the vocabulary website 

- [ ] on the metadata front both JSON-LD and LinkedData we need to reference entities URLs on the vocabulary website and articles URLs on the main website. 
- [ ] the vocabulary is on a dedicated domain/website (i.e. myvocabulary.mywebsite.com)

**Comment by ziodave** [comment]
Are the vocabulary and the main website on the same WordPress instance?

**Comment by ziodave** [comment]
Do the main web site and the vocabulary web site use the same WordPress' theme?

**Comment by cyberandy** [comment]
- Vocabulary website and back-end where editors create content = WordPress
- Main web site = WordPress >> Ghost

**Comment by ziodave** [comment]
List of tasks:

- [ ] Prepare the development environment with a:
- [ ] Ghost instance
- [ ] WordPress instance
- [ ] Develop an integration plugin which pushes to Ghost new posts, receiving the Ghost id in return and updates/deletes the posts accordingly. The plugin should receive also the Ghost permanent URL for the created/updated/deleted post. It is assumed that this URL is permanent i.e. doesn't change once defined.
- [ ] Test this integration.
- [ ] From WordLift's side, provide the required filters to:
- [ ] Mangle the `schema:url`s so that posts URLs are set to Ghost permanent URLs
- [ ] Mangle the WP's own `get_permalink` function so that the permalink returned is the Ghost permanent URL when available.
- [ ] Test this integration.
- [ ] Eventually define http filters to further intercept and mangle URLs.

**Comment by ziodave** [comment]
Closing, feel free to reopen.
