### ISSUE TITLE
View Linked Data link on WordPress Custom Post Type

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#540]
We've seen a case on a client's website where the View Linked Data button on the editor's UI points to: http://lodview.it/lodview/?IRI=http://data.wordlift.io/wl0217/tienda/12_pulgadas. This is not the correct URL and the system throws a http 500 error. 

- Entities in LOD works well, here is an example http://lodview.it/lodview/?IRI=http://data.wordlift.io/wl0217/entity/marcas
- Structured data also works well (https://search.google.com/structured-data/testing-tool/u/0/?url=http://trendmap.es/es/tienda/12-pulgadas/#url=http%3A%2F%2Ftrendmap.es%2Fes%2Ftienda%2F12-pulgadas%2F)

This is the link to the CPT http://trendmap.es/es/tienda/12-pulgadas/

**Comment by ziodave** [comment]
@gcuofano it appears as if the vocabulary path has been changed, in the beginning it was `tienda` and now it's `entity`.

Can you confirm?

**Comment by daylanKifky** [comment]
Hi, I'm the creator of the site.
The vocabulary path didn't change. ``tienda`` is a _custom post type_ that was active before the plugin was activated.
The problem seems to happen when we try to access to the structured data from a post belonging to this _custom post type_  (so the IRI in loadview starts with `http://data.wordlift.io/wl0217/tienda/` ).
Instead there are not problems trying to visualize the structured data of the default _post type_  (IRI starting with `http://data.wordlift.io/wl0217/post/` ).

**Comment by ziodave** [comment]
Hello @daylanKifky, nice to meet you and thanks for the details. We'll run a test with custom post types and update you.

**Comment by daylanKifky** [comment]
Nice to meet you too, many thanks!

**Comment by ziodave** [comment]
@daylanKifky @gcuofano we identified the issue: WordLift doesn't push custom post types to the cloud Linked Data Store. This is mainly due to the fact that WordLift doesn't know the entity type (whereas a _post_ is a _BlogPosting_ and _entities_ have a taxonomy).

In order to add support for publishing custom post types to the cloud Linked Data Store we need to break up this issue in 3 stages:

1.  allow to define a mapping for custom post types to schema.org types, thus allowing WordLift to publish a minimal amount of properties of the custom post types to the cloud Linked Data Store. Unmapped custom post types won't be published and also shouldn't appear in the local JSON-LD.

2. allow to define a mapping for custom post types properties (standard and meta) to schema.org property types, to allow WordLift to publish additional data to the cloud Linked Data Store. Initial support may be limited to simple properties (simple data type, e.g. 'Address' is a complex data type).

3. allow WordLift to further extend custom post types with well known schema.org properties for the mapped schema.org type.

**Comment by ziodave** [comment]
Adding the _UX_ label and the following user stories:

1. as a user I want WordLift to tell me if there are unmapped custom post types,
2. as a user I want to tell WordLift not to publish a custom post type (i.e. disable publishing to the cloud Linked Data Store, disable JSON-LD, disable SDTT),
3. as a user I want to map a custom post type to a schema.org type (or a custom type),
4. as a user I want to map the custom post type properties (standard - title, body, date published, date created, ... - and meta) to schema.org types (or custom types).

**Comment by ziodave** [comment]
This should be solved in the #428 context.
