### ISSUE TITLE
Make a Content Data export compatible with Google Analytics

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#552]
See https://support.google.com/analytics/answer/3271771?ref_topic=6065609

**Comment by ziodave** [comment]
A couple of helpful queries to generate the export files:

1. 4 Ws:

```
SELECT CONCAT( '/', p.post_name ) AS page_path, m.meta_value AS entity_url, ri.predicate AS w
LINES TERMINATED BY '\n'
 FROM wp_posts p
  INNER JOIN wp_wl_relation_instances ri
   ON ri.subject_id = p.id
  INNER JOIN wp_posts p1
   ON p1.id = ri.object_id AND p1.post_type = 'entity'
  LEFT JOIN wp_postmeta m
   ON m.post_id = p1.id AND m.meta_key = 'entity_url'
 WHERE p.post_type IN ('page', 'post');
```

2. Entity Types:

```
SELECT CONCAT( '/', p.post_name ) AS page_path, p1.post_name AS entity, t.slug AS entity_type  
FROM wp_posts p   INNER JOIN wp_wl_relation_instances ri    ON ri.subject_id = p.id   INNER JOIN wp_posts p1    ON p1.id = ri.object_id AND p1.post_type = 'entity'   INNER JOIN wp_term_relationships tr    ON tr.object_id = p1.id   INNER JOIN wp_term_taxonomy tt    ON tt.term_taxonomy_id = tr.term_taxonomy_id AND tt.taxonomy = 'wl_entity_type'   INNER JOIN fyipm_terms t    ON t.term_id = tt.term_id  WHERE p.post_type IN ('page', 'post');
```

**Comment by ziodave** [comment]
The button in the Download Data should be available only when specifically set with a constant in order to avoid confusing the publisher about this feature.

**Comment by cyberandy** [comment]
A special thanks goes to @mreichhart for helping us fix the query to generate the file and for being the first one in testing this out 💪 . Here is the right query to implement:

```
SELECT CONCAT('/de/',p.post_name,'/') AS 'ga:pagePath', p1.post_name AS 'ga:dimension2', t.slug AS 'ga:dimension3'
 FROM wp_posts p
  INNER JOIN wp_wl_relation_instances ri
   ON ri.subject_id = p.id
  INNER JOIN wp_posts p1
   ON p1.id = ri.object_id AND p1.post_type = 'entity'
  INNER JOIN wp_term_relationships tr
   ON tr.object_id = p1.id
  INNER JOIN wp_term_taxonomy tt
   ON tt.term_taxonomy_id = tr.term_taxonomy_id AND tt.taxonomy = 'wl_entity_type'
  INNER JOIN wp_terms t
   ON t.term_id = tt.term_id
 WHERE p.post_type IN ( 'page', 'post' );
```
By uploading entities as content metadata to Google Analytics we can get a much richer view of site performance.

**Comment by cyberandy** [comment]
In terms of UX, for the time beeing we can enable the feature with a configuration settings and, add the link from the download data tab.

**Comment by markkap** [comment]
@Stoyan0v code review ;)

- [ ] Since this goes into 3.16. lets fix all the relevant functions doc blocks

- [ ] wl_check_permalink_structure needs a better documentation of what it does and returns. I am actually not sure it works correctly right now for the default premalink settings which if I got the feature correctly should let you generate a CSV. this might degrade into a bigger question on how exactly the feature should actually work which will question the validity of the SQL query....

- [ ] The export function should generate output and die. it can not just return for wrong premalink stracture as this will export the html of the home page

- [ ] If the permalink structure is not supported we need to figure out a way to 1. let the user know he make the correct config changes. 2. that the functionality is not available

- [ ] very very minor - I personally do not like concats that can be written in php and be much more readable, to be offloaded to the DB. but up to you.

- [ ] We use wp_die, die, and exit all over IMHO wp_die is the better option.

- [ ] Why do we need the traansient? IMHO it is just confusing to the user that have no idea that the generate info is cached. 

- [ ] Add date to the generated file.

- [ ] CSV should not be html escaped. If it needs any escaping at all it should be a CSV centered one. Maybe the easiest thing to do is to simply use fputcsv 

- [ ] Need to do unit tests. Obvious for wl_check_permalink_structure, but export probably needs to be restructured to the core generating CSV that is easier to test, and leave in the export itself only the validity checks and actual output generation. (unless you want to write test that simulate the whole ajax request ;) there are UT that do it.)

**Comment by markkap** [comment]
@cyberandy @ziodave , I guess you have to answer the question about whether this feature is limited to only one permalink structure.

The sql query as is used here seems to assume a "%postname% permalink structure, which is not the wordpress default one, and it also assumes entities are only under the "entity" post type, which starting with 3.15 will not be correct any longer.

So I guess the question is should this feature be specified by the explicit SQL here, or a more general description (map whatever entities to whatever they reference based on wordpress's actual url of the content). If we do limit it to a specific URL structure we need some kind of indication for the user when he sets the flag in the config but still do not see the button because it is the wrong permalink structure.

**Comment by ziodave** [comment]
@markkap due to the specifics of the query, right now it can work only with the `%postname%` permalink structure and is limited to the _entity_ post type.

This is going to be a limited feature that we enable on specific web sites, so I believe these limitations are fine for the time being.

We can however open a follow up task to extend support to #428 custom post types and other structure, with a low priority for the time being.

In the follow up task we should also decide whether to move this kind of processing (that on WP could be too heavy) to the server (which is also easier to implement).

**Comment by Stoyan0v** [comment]
Hey @markkap , thanks again for your review, it's very good (as always :) ).
You were right that with current code it will hard for me to add UT, so I followed your suggestions and split the login in separate methods that can be easily tested. I will appreciate if you can make another review :)

There is also a small, but nice feature, that I've added to this PR. If you have  `WL_CONFIG_DOWNLOAD_GA_CONTENT_DATA` constant defined, but the permalink structure is different from `/%postname%/`, you will see this hint box, that will be displayed when you click or hover over the button:

![hint](https://cldup.com/_Y9S13cr8n.thumb.png) 

If the permalink structure is ok, then it will be removed and the button will look like the other buttons.

>Probably need to check that the user is admin or maybe in more general way, can admin entities before doing anything. Right now any subscriber can download the data (guess we need to look at the other download for this as well)

I agree, but you can download the data if you know how to do that. Currently the "Download your data" is available to admins only, which prevent other roles to download the data. I'm not sure that we could prevent users from downloading their data, especially the data that is created by the cloud (if they have the link, they can access it directly). We may need new issue for this.

**Comment by ziodave** [comment]
@Stoyan0v @markkap please remember that this button must be visible only if we enable a constant in the `wp-config.php` file (similar to what we did with Batch Analysis), as we don't want to confuse the users with a niche feature.

**Comment by Stoyan0v** [comment]
@ziodave It currently works the same way. 

* If the constant is not defined, nothing is being displayed.
* If the constant is defined, but the permalink structure is not `postname`, the button is displayed, but it's not active.
* If the constant and permalink structure are ok, then the button is active and allow you to download GA data.

**Comment by cyberandy** [comment]
Right now we support only basic permalink configuration. I will re-open the issue to make sure we extend the support to any type of permalink.

**Comment by cyberandy** [comment]
Opening a new issue instead
