### ISSUE TITLE
Add the capability to create new entities in the vocabulary 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#561]
The user story is the following: 

- as _editor in chief_ of the website or as _seo expert_ I want to be able to create new entities in the vocabulary 
- at the same time as _editor in chief_ of the website, I would like to prevent others' from creating new entities

**Comment by cyberandy** [comment]
This has been requested also by another editorial team.

**Comment by ziodave** [comment]
I think this should go right after #467, so that we enable ppl not able to create entities, at least to select existing ones.

**Comment by ziodave** [comment]
@markkap can you define the specs here, should we rely on capabilities/roles?

**Comment by markkap** [comment]
The easiest general answer I think is to add a capability to create entities and assign it by default to editors and admins. Once we have the capability setting it should be trivial to use a role manager plugin or to write a snippet to have a more granular control over who has the capability.

Going more general, it is possible to add such an option to the user profile, but to me it sounds like this kind of UI should not be part of the plugin be default

**Comment by ziodave** [comment]
@markkap the solution you described looks good. I think at the end we need to provide a snippet, as we cannot force someone to install another plugin.

The capability should work also in the opposite way, i.e. I can add the capability to a _Collaborator_.

I imagine something like a checkbox in the user profile:
* [ ] can create entries in the vocabulary

If user cannot create entries in the vocabulary, then also the analysis request should set the property `scope` to `local` when requesting analyses to WLS.

**Comment by ziodave** [comment]
Hello @markkap,

I made some changes to the code:

* merging back _develop_ and fixing some merge conflicts
* renaming `enable_editor_entity_editing` to `allow_editor_entity_editing` to be consistent with the other function `deny_editor_entity_editing`
* renaming the meta key from `wl_deny_edit_entity` to `_wl_deny_entity_edit` to be consistent with the other meta keys and with the constant name
* fixing some `@since` errors in the comments
* refactor code according to DRY principles, i.e. this
```
	public function deny_editor_entity_editing( $user_id ) {
		 $user = get_user_by( 'id', $user_id );

		 // Only editors are handled in the profile UI, ignore the rest.
		if ( in_array( 'editor', (array) $user->roles ) ) {
			 // The user explicitly do not have the capability.
			 update_user_meta( $user_id, self::DENY_ENTITY_EDIT_META_KEY, true );
		}
	}

	public function allow_editor_entity_editing( $user_id ) {
		 $user = get_user_by( 'id', $user_id );

		 // Only editors are handled in the profile UI, ignore the rest.
		if ( in_array( 'editor', (array) $user->roles ) ) {
			 // The user explicitly do not have the capability.
			 delete_user_meta( $user_id, self::DENY_ENTITY_EDIT_META_KEY );
		}
	}
```

becomes:
	public function deny_editor_entity_editing( $user_id ) {

		// Bail out if the user is not an editor.
		if ( ! $this->is_editor( $user_id ) ) {
			return;
		}

		// The user explicitly do not have the capability.
		update_user_meta( $user_id, self::DENY_ENTITY_EDIT_META_KEY, true );
		
	}

	public function allow_editor_entity_editing( $user_id ) {

		// Bail out if the user is not an editor.
		if ( ! $this->is_editor( $user_id ) ) {
			return;
		}

		// The user explicitly do not have the capability.
		delete_user_meta( $user_id, self::DENY_ENTITY_EDIT_META_KEY );

	}

	private function is_editor( $user_id ) {

		// Get the user.
		$user = get_user_by( 'id', $user_id );

		// Return true, if the user is found and has the `editor` role.
		return is_a( $user, 'WP_User' ) && in_array( 'editor', (array) $user->roles );
	}

This also applies `function editor_can_create_entities( $user_id )`.

* changed this `<?php if ( in_array( 'editor', (array) $user->roles ) ) { ?>` in src/admin/class-wordlift-admin-user-profile-page.php to `<?php if ( $this->user_service->is_editor( $user->ID ) ) { ?>` to be consistent with the changes above.
* renamed `wl_can_edit_entities` to `wl_can_create_entities` and `editor_can_edit_entities` to `editor_can_create_entities` and `_editor_entity_editing` to `_editor_entity_create` and `DENY_ENTITY_EDIT_META_KEY` `DENY_ENTITY_CREATE_META_KEY` in order to be consistent with the goal of this issue
* changing this `Wordlift_User_Service::get_instance()` to `$this->user_service` since there's a local `$user_service` instance in src/admin/class-wordlift-admin-user-profile-page.php
* I think this deserves some comments: `'capability_type'       => array( 'wordlift_entity', 'wordlift_entities' )`
* I don't think this is right:
```
	public function save_post( $post_id, $post, $update ) {

		// Avoid doing anything if post is autosave or a revision.
		if ( wp_is_post_autosave( $post ) || wp_is_post_revision( $post ) ) {
			return;
		}

		// Bail out if the user do not have the capability to edit the entity.
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
```

Specifically `if ( ! current_user_can( 'edit_post', $post_id ) ) {` looks wrong here, since the post has already been saved (`function save_post` is hooked to the `save_post` action). Am I right?

* changed this `self::editor_can_create_entities` into `$this->editor_can_create_entities` since `editor_can_create_entities` isn't static
* I don't understand this function
```
	public function editor_can_create_entities( $user_id ) {

		// If not an editor just return true.
		$user = get_user_by( 'id', $user_id );
		if ( ! in_array( 'editor', (array) $user->roles ) ) {
			return true;
		}

		// Check if the user explicitly denied.
		$deny = get_user_meta( $user_id, self::DENY_ENTITY_EDIT_META_KEY, true );
		if ( $deny ) {
			return false;
		}

		return true;
	}
```

Are we saying that whoever is editor is not subject to this flag?
* What about this `public function has_cap( $allcaps, $cap, $args )` in src/includes/class-wordlift-user-service.php, it looks to me that we're deny editing, but we should only deny creating (see the issue description).

**Comment by markkap** [comment]
@ziodave regarding the `save_post` hook:
We discussed protecting the meta, and as illustrated by your comment I do not think it is really useful. Anyone that will get there is not following the normal wordpress admin flow, so the code is useful only if we have alternative flows which might cause that action to be triggered for entities. I am voting for the removal of that check.

`editor_can_create_entities`:
It probably needs a better name. The only thing that we care about there is if the user is an editor which is explicitly denied from editing entities. in which case we return a false. For the rest we return a true as a sign of "do not care" more than an affirmative that the user "can"
This relates to its usage in `has_cap``. We do not want to deny/enable more then we explicitly aim for in order not to block the ability of other plugin to add the capability to users which are not editors, or other roles, all we care about is users that are editors, and the UI in the profile is displayed only for editors.

**Comment by ziodave** [comment]
> We discussed protecting the meta, and as illustrated by your comment I do not think it is really useful. Anyone that will get there is not following the normal wordpress admin flow, so the code is useful only if we have alternative flows which might cause that action to be triggered for entities. I am voting for the removal of that check.

Agreed.

> `editor_can_create_entities`:  It probably needs a better name. The only thing that we care about there is if the user is an editor which is explicitly denied from editing entities. in which case we return a false. For the rest we return a true as a sign of "do not care" more than an affirmative that the user "can".
> This relates to its usage in has_cap. We do not want to deny/enable more then we explicitly aim for in order not to block the ability of other plugin to add the capability to users which are not editors, or other roles, all we care about is users that are editors, and the UI in the profile is displayed only for editors.

I have 2 questions:
1. as an editor with the _deny_ flag on, can I edit existing entities?
2. what happens if I am a contributor?

**Comment by markkap** [comment]
@ziodave 

> as an editor with the deny flag on, can I edit existing entities?
Assuming no bugs, the answer is "no". You should not even get the relevant admin menus in that case.

> what happens if I am a contributor?
OK, so lets take one step back
in the upgrade/db initialization process we assign all the relevant capabilities to the roles of "administrator" and "editor". Role capabilities are a fallback for user capabilities. In a way user capabilities exist to have a fine grain tuning of role capabilities. 
End result is that users which are in roles other than editor and administrator will be denied editing without having any specific code for that.
We do not add UI in the user profile to enable a contributor to edit entities because it is almost always will be useless clutter, but people can use a capabilities and role manager plugin, or have their own filter over the user capabilities to add the capability to the a contributor or any other user.

**Comment by ziodave** [comment]
> as an editor with the deny flag on, can I edit existing entities?
Assuming no bugs, the answer is "no". You should not even get the relevant admin menus in that case.

Ok, we need to check this, because the issue was only about denying creating new entities, not denying editing existing one. @cyberandy can you please let us know if the current implementation (i.e. deny create/edit on existing entities, non-editors don't see the vocabulary at all) is fine?

> End result is that users which are in roles other than editor and administrator will be denied editing without having any specific code for that.

👍

**Comment by markkap** [comment]
@ziodave @cyberandy I have added all the capabilities I saw as relevant as "one block", if you have one you should have all. I do not see a value in create without being able to edit, and in edit without being able to delete, but there are some advanced possibilities that might make sense like not letting an editor edit entities that are created by someone else.

**Comment by ziodave** [comment]
@markkap yes, I understand the logic and it makes sense, I want to be sure it satisfies the original requirement though.

**Comment by cyberandy** [comment]
@makkap @ziodave the implementation fits the requirements: either I have the capabilities to create and edit or I don't. In this second scenario I don't even need to see the vocabulary, I can only tag by using entities already in the vocabulary. No need at this stage for more options than this. Great work!
