### ISSUE TITLE
Using the mention property (or similar) to describe an article that is annotated with a Recipe 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#605]
See for instance "Uralub am bauernhof" on SLT

**Comment by ziodave** [comment]
Beatiful: 
![image](https://user-images.githubusercontent.com/11438/29749774-930bdb66-8b3c-11e7-803d-480d83966c01.png)

**Comment by ziodave** [comment]
If we're talking about this URL, https://www.salzburgerland.com/de/urlaub-am-bauernhof/, this is not feasible since that page is an entity page for an Organization:

![image](https://user-images.githubusercontent.com/11438/29749804-256311a0-8b3d-11e7-99e1-ceb2de958a0e.png)

An Organization has no _mention_ property.

**Comment by mreichhart** [comment]
The problem here is, that the snippet shows the properties and the image of a recipe which is annotated in the text. The entity page is about the organization "Urlaub am Bauernhof" (farm holidays), so showing the recipe properties in the result is misleading.

**Comment by ziodave** [comment]
Hello @mreichhart, the markup is just fine (the _mainEntityOfPage_ is correctly set for the Organization to https://www.salzburgerland.com/de/urlaub-am-bauernhof/ and for the Recipe to https://www.salzburgerland.com/de/bauernkrapfen/).

If the Google Preview as it is now is undesirable (and I agree it is not), the best course of action is to clear the Recipe entity selection from the Organization entity, as there's no way to express that a Recipe is linked to the Organization, and it wouldn't affect Google's Preview anyway even if it existed.

**Comment by cyberandy** [comment]
Hi @jvandriel, any idea on this one? 
Let me summarise the case first. We have an entity `type=Organization` published with a json-ld on  https://www.salzburgerland.com/de/urlaub-am-bauernhof/ (entity id on LOD being [http://open.salzburgerland.com/de/entity/urlaub_am_bauernhof](http://lodview.it/lodview/?IRI=http://open.salzburgerland.com/de/entity/urlaub_am_bauernhof)). 

Now the description of this entity has been annotated with other entities including an entity `type=Recipe` and Google - is displaying in the serp (when searching for "urlaub am bauernhof") the page using the Recipe Rich Card rather than with a normal link and/or with a card for the  Organization.  

This is what we see: 
![image](https://user-images.githubusercontent.com/837037/29775420-5f2659f6-8c05-11e7-8d54-52fbeed8ef5c.png)

This is what we expect to see:
![image](https://user-images.githubusercontent.com/837037/29775556-cce8c37a-8c05-11e7-9351-1292b13ffe4f.png)

Now in the markup, as we're annotating an entity we cannot use (as pointed out by @ziodave), the `mentions` property. Is there anything else, at markup level, that we could do to address this specific case? 

Many thanks in advance!

**Comment by jvandriel** [comment]
What you could do is either (a) remove the recipe markup or (b) add the following markup to the recipe:
```
"publisher":
{
  "@id":"http://open.salzburgerland.com/de/entity/urlaub_am_bauernhof"
}
```

Personally I'd go for option (a) as the ```Recipe``` contains much more information than is present on https://www.salzburgerland.com/de/urlaub-am-bauernhof/. A situation that might cause Google to give a manual structured data penalty due to marking up information that isn't present on the page (which goes against their guidelines).

If the markup would have been limited to the info present on the pages, than there isn't any risk for getting such a penalty and than option (b) would be fine, eg:
```
"@type":"Recipe",
"@id":"http://open.salzburgerland.com/de/entity/bauernkrapfen",
"mainEntityOfPage":"https://www.salzburgerland.com/de/bauernkrapfen/",
"name":"Bauernkrapfen",
"publisher":
{
  "@id":"http://open.salzburgerland.com/de/entity/urlaub_am_bauernhof"
}
```

**Comment by cyberandy** [comment]
Thanks, @jvandriel for your reply. Basically, as the page is not containing any specific information about the recipe we shall simply _de-select the annotation_ and eventually, add a manual href link to the entity page of the `Recipe` - option (a). 

Adding the full markup only makes sense if the `Recipe` information is present on the page.
@mreichhart does it make sense to you?

**Comment by mreichhart** [comment]
In my opinion this is a fundamental decision whether to annotate entities or not. The same could happen if  another entity type (eg person) is selected/annotated that is containing much information.

Now in the markup the entity itself an all annotated entities are at the same level. Wouldn't it be more accurate to markup the entity itself as is and create nested markup for annotated entites using "WebPage" scheme with "mentions" property?

**Comment by ziodave** [comment]
That wouldn't solve, because Google will display the preview for an annotated _Recipe_, just because it's annotated and has enough information for the preview, independently whether it's linked from _mentions_, _about_ or unlinked.

**Comment by mreichhart** [comment]
Ok. So the best solution for us is to annotate a _Recipe_ only if it is the main entity of the article/entity and we want Google to display the _Recipe_ snippet or card.

**Comment by ziodave** [comment]
Correct. Even if it's not the main entity, but enough _Recipe_ information are displayed in page and you're okay with Google showing the preview of the Recipe for that page.

**Comment by jvandriel** [comment]
As a rule Google treats the entity that contains the most data as the ```mainEntityOfPage``` - when this property hasn't been specified, yet if the ```mainEntity``` (inverse property) of a page doesn't contain contain sufficient data to generate an enriched search result for than Google can choose another entity - that does contain sufficient data - as a source for the SERP snippet

On top of that all other _top level entities_ are treated as being ```mentions``` of the ```WebPage```. Meaning, chaining secondary entities to a ```WebPage``` through the ```mentions``` property can be done but since it's already implied for secondary entities it's could be considered markup overkill.

And lastly, in regards to:
> _as the page is not containing any specific information about the recipe_

That's a *key* guideline @cyberandy, the number one rule for not getting a structured data penalty is limit yourself to only adding markup for those types and properties that are present in the HTML of a page (besides properties like ```@id```,```sameAs```,```url```,etc). 

So if you really want to you can chain secondary entities to the ```WebPage``` through the ```mentions``` property as such:
```
<script type="application/ld+json">
[
  {
    "@context":"https://schema.org",
    "@id":"https://www.salzburgerland.com/de/urlaub-am-bauernhof/",
    "@type": "WebPage"
  },
  {
    "@context":"https://schema.org",
    "@type":"Recipe",
    "@reverse":
    {
      "mentions":
      {
        "@id":"https://www.salzburgerland.com/de/urlaub-am-bauernhof/"
      }
    },
    "url":"https://www.salzburgerland.com/de/bauernkrapfen/"
  }
]
</script>
```

**Comment by cyberandy** [comment]
Thanks @jvandriel for the added information. The rule is clear:

> add only markup for those types and properties that are present in the HTML of a page

In other words, if there is not enough information on the page and if we don't want Google to present the Rich Card, we shall not annotate the entity.
