### ISSUE TITLE
Check WL compatibility with ACF 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#659]
On a client website apparently when WordLift is enabled the ACF disappears. When WL gets disabled, the ACF appear again. 

Procedure to replicate the issue: 

1. Deactive Wordlift first and create on ACF a form. (I already made one "Hotel Review WordLift") 
2. Activate Wordlift plugin
3. Go to ACF and open the form. 
4. Just add any new input item on that form and press save
5. You will notice that the form will be blank, every item is removed. 
6. If you try to save again, it saves but remains blank. 

Note: existing ACF forms remain fine as long as you do not edit them. Wordlift is active on the site so the procedure to replicate the issue can be started from step 3.

**Comment by ziodave** [comment]
I checked on the web site and ACF isn't there.

**Comment by ziodave** [comment]
Indeed ACF is included in the Travelo theme. The issue is that WordLift's classification box was being loaded on the ACF settings screen (even though there's no editor).

I added a check to `wl_admin_add_entities_meta_box` (src/admin/wordlift_admin_meta_box_entities.php) to avoid loading WordLift's classification box when there's no editor.
