### ISSUE TITLE
Nested span issue and wrong annotations

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin#675]
Please see screenshot below:

![085e0ea7-d088-4dfe-9ca7-66e2fc114a09](https://user-images.githubusercontent.com/837037/31812890-be579e5a-b584-11e7-8c46-172cde5028c3.jpg)

See here:  https://www.salzburgerland.com/de/wp-admin/post.php?post=60186&action=edit

**Comment by ziodave** [comment]
How to reproduce it?

This is what I see when I open the link:
![image](https://user-images.githubusercontent.com/11438/31819473-091ce4f0-b59d-11e7-92ab-6afe0de9e91f.png)

**Comment by ziodave** [comment]
Ok, I see it.

**Comment by ziodave** [comment]
I manually cleanup the page. I need more information how to reproduce this error. Is it possible that some annotations are inserted manually or that the text is copied pasted from some editor (such as Word)?

I am asking because I saw a text annotation around this text "Info: Tourismusverband Mariapfarr" which is unlikely (due to the colon) and also some encoded characters:
![image](https://user-images.githubusercontent.com/11438/31819960-4ab0a472-b59f-11e7-8ad2-024739cb8f90.png)

**Comment by ziodave** [comment]
This should be fix with the latest regex. Feel free to reopen in case of issues.
