### ISSUE TITLE
Search in Vocabulary returns also non-entity posts

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#680]
Please describe the issue here:

When searching for entities in the Dashboard / Vocabulary page, also non-entity posts are returned.

Please provide additional data about your WordPress install:
*[ ] WordPress version: 4.8
*[ ] WordLift plugin version: 3.15.3
*[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: login to the Dashboard.
 - Step 2: go the Vocabulary.
 - Step 3: search for any term (matching at least a non-entity post).
 - Step 4: non-entity posts are returned in the search results.

**Comment by Stoyan0v** [comment]
I've tested with the WordLift and WordPress versions provided, but I'm unable to reproduce the issue (as described). The search brings the correct results every time.

Except the following case:

1. I have a post with name "Test" and entity with name "Sample Entity". Both posts are without any content
2. When I search for "Test" in the vocabulary I didn't see any results.
3. When I add the word "test" in the "Sample Entity" content the search results returns the "Sample Entity" entity.

This is expected behaviour, because the search query search in both the title and content.
