### ISSUE TITLE
Check compatibility with kk Star plugin 

### ISSUE THREAD

**Issue by gcuofano** [insideout10/wordlift-plugin#704]
kk Star is a plugin that allows the implementation of ratings. 
Apparently when WordLift is active on mobile and desktop the stars at the end of the article stop working. 

![screen shot 2017-11-16 at 18 11 00](https://user-images.githubusercontent.com/26247261/32905285-c9aadf80-caf9-11e7-932e-2809a0c43a97.png)

[ ] WordPress version: 4.9 with SmartTheme
[ ] WordLift plugin version: 3.15.6
[ ] Step-by-step procedure on how to reproduce the issue:
 - Step 1: go on a page where kk Star ratings are present, assign a rating to the page
 - Step 2: activate WordLift 
 - Step 3: go back to the same page and see how ratings, as you tap or click, cannot be assigned

**Comment by ziodave** [comment]
Can you send me a sample URL ?

**Comment by ziodave** [comment]
The issue is with WP Rocket (although I am unsure why it doesn't happen when WordLift is disabled).

Anyway adding the KK Star Ratings JavaScript in the Exclude JS setting of WP Rocket fixed the issue:

![image](https://user-images.githubusercontent.com/11438/32945119-7c245d88-cb92-11e7-859d-de2047d1999f.png)
