### ISSUE TITLE
avoid http calls to the plugins/wordlift directory

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#834]
Please describe the issue here:

Some hosting providers may block http calls to the plugins folder. Therefore we should stop using angular html templates.

In the meanwhile an .htaccess file like this might help:
```
<IfModule mod_rewrite.c>
    RewriteEngine Off
</IfModule>

<Files *.html>
    order allow,deny
    allow from all
</Files>
```

Please provide additional data about your WordPress install:
* [ ] WordPress version: 4.9.7
* [ ] WordLift plugin version: 3.19.2

**Comment by JialuZhang** [comment]
@ziodave 

In your posted configuration,
```
<IfModule mod_rewrite.c>
    RewriteEngine Off
</IfModule>
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
