### ISSUE TITLE
Minor bug on text annotation

### ISSUE THREAD

**Issue by slim16165** [insideout10/wordlift-plugin#857]
Please describe the issue here:
![image](https://user-images.githubusercontent.com/4086781/46246479-b6283d00-c3fe-11e8-8e99-dd77cc5ae884.png)

Even if the entity "Le Corbusier" is known the proposed text annotation hits only one of the 2 words: "Corbusier"

**Comment by ziodave** [comment]
Hello @slim16165,

Can you please send us the URL for this page?

**Comment by slim16165** [comment]
Of course:
https://www.totaldesign.it/biennale-di-venezia-2012-sezione-architettura-chi-e-il-direttore-david-chipperfield/

**Comment by ziodave** [comment]
"Le Corbusier" has also "Corbusier" as label [1]:

```
rdfs:label | "Corbusier"@it
rdfs:label | "Le Corbusier"@it
```

The NLP is choosing to shorter label. In case you want to highlight the longer label, either try removing the "Corbusier" label from the knowledge graph, or manually select and add the entity annotations.

[1] http://data.wordlift.io/wl0926/entity/le_corbusier.html

**Comment by ziodave** [comment]
I am not sure why I don't read here the reply I received via e-mail:

> Yes.. as a developer I understand how I can make a workaround but..
> The functional reason to insert both "Corbusier" and "Le Corbusier" in the knowledge graph is pretty obvious..
> 
> Is there any functional reason to choose a partial match when you could operate a total match?
> 
> Le Corbusier → total match
> Corbusier → partial match
> 
> Which is the reason, for the algorithm, to choose the worst match?
> 
> If there is none you are suggesting a workaround to a small bug..

The NLP analyzer doesn't know that "Corbusier" is worst than "Le Corbusier" because they're both set as labels (i.e. with equal weight). On top of that it is possible that "Le" is interpreted as an article.

It's not really a (small) bug, maybe a missing feature, such as "allow to define a master label and give it priority in content analysis". It's just something we don't support at the moment.

**Comment by slim16165** [comment]
You are right sorry. 

I had deleted the comment because I thought I was wrong and that it was an insignificant detail.

Thanks for the answer.
