### ISSUE TITLE
Edit post screen displays duplicated values in metabox properties

### ISSUE THREAD

**Issue by ziodave** [insideout10/wordlift-plugin#946]
Please describe the issue here:

![image](https://user-images.githubusercontent.com/11438/64354275-6a631800-cfff-11e9-98f8-89f2df226067.png)

Applies also to _sameAs_.

Please provide additional data about your WordPress install:
[ ] WordPress version: 5.2
[ ] WordLift plugin version: 3.21.4

**Comment by akshayraje** [comment]
@ziodave I was just going through the code to be able to hand-over this to @Sidsector9 but while doing that I realised that this cannot be reproduced locally. theswimmingswan.com is on the latest version of WL plugin and latest version of WP and yet this behaves differently. In-fact this is not even reproducible on alpha.wordlift.io

I think it may be some sort of caching / server side optimization that is causing this at theswimmingswan.com. Let us know how to proceed with this.

**Comment by akshayraje** [comment]
I spent a couple of hours looking into this and it seems this is some site specific intermittent issue. Out of 420+ pages of type LocalBusiness this issue seemed to happen only on 27 pages and I was not able to find out a reason or a pattern when it occurs. Further, this cannot be reproduced locally or on alpha.wordlift.io.

As of now, I have fixed it at the database level by SQL queries and on those same posts, after fixing it can no more be re-produced. My best guess is that this might have been caused due to some object cache or similar issue
